---
ID: "cbe1d397-8994-4c03-a43f-aa8c54b25a90"
Parent: "b8fbdf00-57dc-4bb7-85ec-c34cc401379e"
Template: "b8fbdf00-57dc-4bb7-85ec-c34cc401379e"
Path: /sitecore/templates/Foundation/HztlFoundation/Base/_SeoMetadataPlus/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250417T062438Z
    - ID: "441b6887-d610-4cd5-a972-9098bdd41abf"
      Hint: robotsMetaTag
      Value: index
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "714b65ee-d6c5-44c7-b587-ed42b537df16"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250417T062458Z
