---
ID: "dfb9f94a-3ef8-43de-b13a-07b03cec0a6a"
Parent: "3109db8b-cf49-402b-9864-2ad4fff0a6f4"
Template: "3109db8b-cf49-402b-9864-2ad4fff0a6f4"
Path: /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5b68bb31-dc79-4965-b9bc-24bcbdc4ca88"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250425T080458Z
