// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useEffect, useRef, useCallback, useState, createContext, useContext, useMemo, startTransition } from 'react';
import React from 'react';
import RichTextWrapper from 'helpers/SitecoreWrappers/RichTextWrapper/RichTextWrapper';
import { Placeholder, CdpHelper, useSitecore, Text, Image as Image_8a80e63291fea86e0744df19113dc44bec187216 } from '@sitecore-content-sdk/nextjs';
import Head from 'next/head';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import { nextConfigImages } from 'lib/next-config/plugins/images';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import scConfig from 'sitecore.config';
import { tv } from 'tailwind-variants';
import useDictionary from 'lib/hooks/useDictionary';
import { smoothScrollToElement, useScrollElementIntoView } from 'lib/hooks/useScrollElementIntoView';
import { SvgIcon } from 'helpers/SvgIcon';
import PlainTextWrapper from 'helpers/SitecoreWrappers/PlainTextWrapper/PlainTextWrapper';
import { getTestProps } from 'lib/testing/utils';
import { PlaceholderWrapper } from 'helpers/SitecoreWrappers/PlaceholderWrapper/PlaceholderWrapper';
import { findComponent } from 'lib/utils/object-utils';
import { useRouter } from 'next/router';
import NextLink from 'next/link';
import { useLanguages, useSiteSettings, useCurrentPage } from 'lib/hooks/sitecore/context';
import { useRealPathName } from 'lib/hooks/useRealPathName';
import { useHeader, HeaderProvider } from 'src/components/authorable/shared/site-structure/Header/HeaderContext';
import { capitalizeFirstLetter } from 'lib/utils/string-utils';
import { US, AE, MX, CA, BR } from 'country-flag-icons/react/3x2';
import { Logo } from 'components/authorable/shared/site-structure/Header/HeaderDesktop';
import HeaderDesktop from 'components/authorable/shared/site-structure/Header/HeaderDesktop';
import LanguageSelector from 'src/components/authorable/shared/site-structure/Header/LanguageSelector';
import LinkWrapper from 'helpers/SitecoreWrappers/LinkWrapper/LinkWrapper';
import ImageWrapper from 'helpers/SitecoreWrappers/ImageWrapper/ImageWrapper';
import useClickOutside from 'lib/hooks/useClickOutside';
import PreviewSearchBasicWidget from 'widgets/SearchPreview';
import { useOnRouteChange } from 'lib/hooks/useOnRouteChange';
import { useIsMobile } from 'lib/hooks/useIsMobile';
import { toValidId } from 'lib/utils/validate-id-utils';
import { useIsScrolled } from 'lib/hooks/useIsScrolled';
import HeaderMobile from 'components/authorable/shared/site-structure/Header/HeaderMobile';
import useIsEditing from 'lib/hooks/useIsEditing';
import { SvgImageWrapper } from 'helpers/SitecoreWrappers/SvgImageWrapper/SvgImageWrapper';
import BreadcrumbQuery from 'components/authorable/shared/site-structure/Breadcrumb/Breadcrumb.graphql';
import graphqlClientFactory from 'lib/graphql-client-factory';
import { withStandardComponentWrapper } from 'helpers/HOC';
import RelatedArticlesWidget from 'widgets/RelatedArticles';
import { EditingHelpText } from 'helpers/Editing/EditingHelpText';
import ArticleCategoryTabsQuery from 'components/authorable/shared/page-specific/ArticleCategoryTabs.graphql';
import PopularArticlesWidget from 'widgets/PopularArticles';
import ArticleSearchWidget from 'widgets/ArticleListing';
import ArticleTagsWrapper from 'helpers/GenericWrappers/ArticleTagsWrapper/ArticleTagsWrapper';
import formatDate from 'lib/utils/date-formatter';
import { EditingConditionalRender } from 'helpers/Editing/EditingConditionalRender';
import { ScrollButton } from 'src/components/authorable/shared/lists/Tab';
import { useScrollableTabs } from 'lib/hooks/useScrollableTabs';
import { useSearchResultsActions, useSearchResultsSelectedFilters } from '@sitecore-search/react';
import { SortSelect, Pagination, AccordionFacets, FacetItem, SearchResultsAccordionFacets } from '@sitecore-search/ui';
import { useSearchParams } from 'next/navigation';
import SearchResultsWidget from 'widgets/SearchResult';
import SearchFilterFacets from 'src/components/authorable/shared/page-specific/SearchResult/SearchFilterFacets';
import SearchSelectedFilterTags from 'src/components/authorable/shared/page-specific/SearchResult/SearchSelectedFilterTags';
import { SectionWrapper } from 'helpers/GenericWrappers/SectionWrapper/SectionWrapper';
import { useVideoWidth } from 'lib/hooks/useVideoWidth';
import { getVideoPlatform, getYouTubeEmbedUrl, getVimeoUrl, getProcessedVideoUrl } from 'lib/utils/videoUtils';
import { getNextImageProps } from 'lib/utils/image-utils';
import { EditingFieldValues } from 'helpers/Editing/EditingFieldValues';
import SvgIcon_9b2d61ee97e93b39d0af8347fe490803905dab7b from 'helpers/SvgIcon/SvgIcon';
import { useCardListContext } from 'src/components/authorable/shared/lists/CardList';
import { lockBodyScroll, unlockBodyScroll } from 'lib/utils/scroll-lock';
import { ctaTailwindVariant } from 'helpers/SitecoreWrappers/ButtonWrapper/ButtonWrapper';
import ButtonWrapper from 'helpers/SitecoreWrappers/ButtonWrapper/ButtonWrapper';
import { getCtaStyle } from 'lib/utils/cta-utils';
import { parseStyleParams } from 'lib/utils/style-param-utils';
import { useTab, TabContextProvider } from 'helpers/Context/TabContext';
import CountUp from 'react-countup';
import { BrandAndThemeProvider } from 'lib/context/BrandAndThemeContext';
import { createLinkField, isValidNavigationItem, getValidChildren } from 'lib/utils/navigation-utils';
import { TAILWIND_VARIANTS } from 'src/components/authorable/shared/lists/ContextualNav';
import { CurrentPageQuery, NavigationRootQuery } from 'src/components/authorable/shared/lists/ContextualNav.graphql';
import { useNavigationState } from 'lib/hooks/useNavigationState';
import { ContextualNavItem } from 'src/components/authorable/shared/lists/ContextualNavItem';
import { Intersection } from '@splidejs/splide-extension-intersection';
import { Splide, SplideSlide, SplideTrack } from '@splidejs/react-splide';
import { useAccordionItemContext, AccordionContextProvider, useAccordionContext } from 'helpers/Context/AccordionContext';
import { TextAlignmentProvider } from 'lib/context/TextAlignmentContext';
import { useWatchJumpNavActiveState, JumpNavContextProvider, useJumpNavContext, useMainHeaderHeight } from 'helpers/Context/JumpNavContext';
import { focusUnfocusableElement } from 'lib/utils/dom-utils/tab';
import clsx from 'clsx';
import ModalWrapper from 'helpers/GenericWrappers/ModalWrapper/ModalWrapper';
import Script from 'next/script';
import { getScriptUrl } from 'lib/utils/link-utils';
import useIsNormalMode from 'lib/hooks/useIsNormalMode';
import Cookies from 'js-cookie';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'useRef', value: useRef },
      { name: 'useCallback', value: useCallback },
      { name: 'useState', value: useState },
      { name: 'createContext', value: createContext },
      { name: 'useContext', value: useContext },
      { name: 'useMemo', value: useMemo },
      { name: 'startTransition', value: startTransition },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'helpers/SitecoreWrappers/RichTextWrapper/RichTextWrapper',
    exports: [
      { name: 'default', value: RichTextWrapper },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Placeholder', value: Placeholder },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'useSitecore', value: useSitecore },
      { name: 'Text', value: Text },
      { name: 'Image', value: Image_8a80e63291fea86e0744df19113dc44bec187216 },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'lib/next-config/plugins/images',
    exports: [
      { name: 'nextConfigImages', value: nextConfigImages },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: scConfig },
    ]
  },
  {
    module: 'tailwind-variants',
    exports: [
      { name: 'tv', value: tv },
    ]
  },
  {
    module: 'lib/hooks/useDictionary',
    exports: [
      { name: 'default', value: useDictionary },
    ]
  },
  {
    module: 'lib/hooks/useScrollElementIntoView',
    exports: [
      { name: 'smoothScrollToElement', value: smoothScrollToElement },
      { name: 'useScrollElementIntoView', value: useScrollElementIntoView },
    ]
  },
  {
    module: 'helpers/SvgIcon',
    exports: [
      { name: 'SvgIcon', value: SvgIcon },
    ]
  },
  {
    module: 'helpers/SitecoreWrappers/PlainTextWrapper/PlainTextWrapper',
    exports: [
      { name: 'default', value: PlainTextWrapper },
    ]
  },
  {
    module: 'lib/testing/utils',
    exports: [
      { name: 'getTestProps', value: getTestProps },
    ]
  },
  {
    module: 'helpers/SitecoreWrappers/PlaceholderWrapper/PlaceholderWrapper',
    exports: [
      { name: 'PlaceholderWrapper', value: PlaceholderWrapper },
    ]
  },
  {
    module: 'lib/utils/object-utils',
    exports: [
      { name: 'findComponent', value: findComponent },
    ]
  },
  {
    module: 'next/router',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: NextLink },
    ]
  },
  {
    module: 'lib/hooks/sitecore/context',
    exports: [
      { name: 'useLanguages', value: useLanguages },
      { name: 'useSiteSettings', value: useSiteSettings },
      { name: 'useCurrentPage', value: useCurrentPage },
    ]
  },
  {
    module: 'lib/hooks/useRealPathName',
    exports: [
      { name: 'useRealPathName', value: useRealPathName },
    ]
  },
  {
    module: 'src/components/authorable/shared/site-structure/Header/HeaderContext',
    exports: [
      { name: 'useHeader', value: useHeader },
      { name: 'HeaderProvider', value: HeaderProvider },
    ]
  },
  {
    module: 'lib/utils/string-utils',
    exports: [
      { name: 'capitalizeFirstLetter', value: capitalizeFirstLetter },
    ]
  },
  {
    module: 'country-flag-icons/react/3x2',
    exports: [
      { name: 'US', value: US },
      { name: 'AE', value: AE },
      { name: 'MX', value: MX },
      { name: 'CA', value: CA },
      { name: 'BR', value: BR },
    ]
  },
  {
    module: 'components/authorable/shared/site-structure/Header/HeaderDesktop',
    exports: [
      { name: 'Logo', value: Logo },
      { name: 'default', value: HeaderDesktop },
    ]
  },
  {
    module: 'src/components/authorable/shared/site-structure/Header/LanguageSelector',
    exports: [
      { name: 'default', value: LanguageSelector },
    ]
  },
  {
    module: 'helpers/SitecoreWrappers/LinkWrapper/LinkWrapper',
    exports: [
      { name: 'default', value: LinkWrapper },
    ]
  },
  {
    module: 'helpers/SitecoreWrappers/ImageWrapper/ImageWrapper',
    exports: [
      { name: 'default', value: ImageWrapper },
    ]
  },
  {
    module: 'lib/hooks/useClickOutside',
    exports: [
      { name: 'default', value: useClickOutside },
    ]
  },
  {
    module: 'widgets/SearchPreview',
    exports: [
      { name: 'default', value: PreviewSearchBasicWidget },
    ]
  },
  {
    module: 'lib/hooks/useOnRouteChange',
    exports: [
      { name: 'useOnRouteChange', value: useOnRouteChange },
    ]
  },
  {
    module: 'lib/hooks/useIsMobile',
    exports: [
      { name: 'useIsMobile', value: useIsMobile },
    ]
  },
  {
    module: 'lib/utils/validate-id-utils',
    exports: [
      { name: 'toValidId', value: toValidId },
    ]
  },
  {
    module: 'lib/hooks/useIsScrolled',
    exports: [
      { name: 'useIsScrolled', value: useIsScrolled },
    ]
  },
  {
    module: 'components/authorable/shared/site-structure/Header/HeaderMobile',
    exports: [
      { name: 'default', value: HeaderMobile },
    ]
  },
  {
    module: 'lib/hooks/useIsEditing',
    exports: [
      { name: 'default', value: useIsEditing },
    ]
  },
  {
    module: 'helpers/SitecoreWrappers/SvgImageWrapper/SvgImageWrapper',
    exports: [
      { name: 'SvgImageWrapper', value: SvgImageWrapper },
    ]
  },
  {
    module: 'components/authorable/shared/site-structure/Breadcrumb/Breadcrumb.graphql',
    exports: [
      { name: 'default', value: BreadcrumbQuery },
    ]
  },
  {
    module: 'lib/graphql-client-factory',
    exports: [
      { name: 'default', value: graphqlClientFactory },
    ]
  },
  {
    module: 'helpers/HOC',
    exports: [
      { name: 'withStandardComponentWrapper', value: withStandardComponentWrapper },
    ]
  },
  {
    module: 'widgets/RelatedArticles',
    exports: [
      { name: 'default', value: RelatedArticlesWidget },
    ]
  },
  {
    module: 'helpers/Editing/EditingHelpText',
    exports: [
      { name: 'EditingHelpText', value: EditingHelpText },
    ]
  },
  {
    module: 'components/authorable/shared/page-specific/ArticleCategoryTabs.graphql',
    exports: [
      { name: 'default', value: ArticleCategoryTabsQuery },
    ]
  },
  {
    module: 'widgets/PopularArticles',
    exports: [
      { name: 'default', value: PopularArticlesWidget },
    ]
  },
  {
    module: 'widgets/ArticleListing',
    exports: [
      { name: 'default', value: ArticleSearchWidget },
    ]
  },
  {
    module: 'helpers/GenericWrappers/ArticleTagsWrapper/ArticleTagsWrapper',
    exports: [
      { name: 'default', value: ArticleTagsWrapper },
    ]
  },
  {
    module: 'lib/utils/date-formatter',
    exports: [
      { name: 'default', value: formatDate },
    ]
  },
  {
    module: 'helpers/Editing/EditingConditionalRender',
    exports: [
      { name: 'EditingConditionalRender', value: EditingConditionalRender },
    ]
  },
  {
    module: 'src/components/authorable/shared/lists/Tab',
    exports: [
      { name: 'ScrollButton', value: ScrollButton },
    ]
  },
  {
    module: 'lib/hooks/useScrollableTabs',
    exports: [
      { name: 'useScrollableTabs', value: useScrollableTabs },
    ]
  },
  {
    module: '@sitecore-search/react',
    exports: [
      { name: 'useSearchResultsActions', value: useSearchResultsActions },
      { name: 'useSearchResultsSelectedFilters', value: useSearchResultsSelectedFilters },
    ]
  },
  {
    module: '@sitecore-search/ui',
    exports: [
      { name: 'SortSelect', value: SortSelect },
      { name: 'Pagination', value: Pagination },
      { name: 'AccordionFacets', value: AccordionFacets },
      { name: 'FacetItem', value: FacetItem },
      { name: 'SearchResultsAccordionFacets', value: SearchResultsAccordionFacets },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'useSearchParams', value: useSearchParams },
    ]
  },
  {
    module: 'widgets/SearchResult',
    exports: [
      { name: 'default', value: SearchResultsWidget },
    ]
  },
  {
    module: 'src/components/authorable/shared/page-specific/SearchResult/SearchFilterFacets',
    exports: [
      { name: 'default', value: SearchFilterFacets },
    ]
  },
  {
    module: 'src/components/authorable/shared/page-specific/SearchResult/SearchSelectedFilterTags',
    exports: [
      { name: 'default', value: SearchSelectedFilterTags },
    ]
  },
  {
    module: 'helpers/GenericWrappers/SectionWrapper/SectionWrapper',
    exports: [
      { name: 'SectionWrapper', value: SectionWrapper },
    ]
  },
  {
    module: 'lib/hooks/useVideoWidth',
    exports: [
      { name: 'useVideoWidth', value: useVideoWidth },
    ]
  },
  {
    module: 'lib/utils/videoUtils',
    exports: [
      { name: 'getVideoPlatform', value: getVideoPlatform },
      { name: 'getYouTubeEmbedUrl', value: getYouTubeEmbedUrl },
      { name: 'getVimeoUrl', value: getVimeoUrl },
      { name: 'getProcessedVideoUrl', value: getProcessedVideoUrl },
    ]
  },
  {
    module: 'lib/utils/image-utils',
    exports: [
      { name: 'getNextImageProps', value: getNextImageProps },
    ]
  },
  {
    module: 'helpers/Editing/EditingFieldValues',
    exports: [
      { name: 'EditingFieldValues', value: EditingFieldValues },
    ]
  },
  {
    module: 'helpers/SvgIcon/SvgIcon',
    exports: [
      { name: 'default', value: SvgIcon_9b2d61ee97e93b39d0af8347fe490803905dab7b },
    ]
  },
  {
    module: 'src/components/authorable/shared/lists/CardList',
    exports: [
      { name: 'useCardListContext', value: useCardListContext },
    ]
  },
  {
    module: 'lib/utils/scroll-lock',
    exports: [
      { name: 'lockBodyScroll', value: lockBodyScroll },
      { name: 'unlockBodyScroll', value: unlockBodyScroll },
    ]
  },
  {
    module: 'helpers/SitecoreWrappers/ButtonWrapper/ButtonWrapper',
    exports: [
      { name: 'ctaTailwindVariant', value: ctaTailwindVariant },
      { name: 'default', value: ButtonWrapper },
    ]
  },
  {
    module: 'lib/utils/cta-utils',
    exports: [
      { name: 'getCtaStyle', value: getCtaStyle },
    ]
  },
  {
    module: 'lib/utils/style-param-utils',
    exports: [
      { name: 'parseStyleParams', value: parseStyleParams },
    ]
  },
  {
    module: 'helpers/Context/TabContext',
    exports: [
      { name: 'useTab', value: useTab },
      { name: 'TabContextProvider', value: TabContextProvider },
    ]
  },
  {
    module: 'react-countup',
    exports: [
      { name: 'default', value: CountUp },
    ]
  },
  {
    module: 'lib/context/BrandAndThemeContext',
    exports: [
      { name: 'BrandAndThemeProvider', value: BrandAndThemeProvider },
    ]
  },
  {
    module: 'lib/utils/navigation-utils',
    exports: [
      { name: 'createLinkField', value: createLinkField },
      { name: 'isValidNavigationItem', value: isValidNavigationItem },
      { name: 'getValidChildren', value: getValidChildren },
    ]
  },
  {
    module: 'src/components/authorable/shared/lists/ContextualNav',
    exports: [
      { name: 'TAILWIND_VARIANTS', value: TAILWIND_VARIANTS },
    ]
  },
  {
    module: 'src/components/authorable/shared/lists/ContextualNav.graphql',
    exports: [
      { name: 'CurrentPageQuery', value: CurrentPageQuery },
      { name: 'NavigationRootQuery', value: NavigationRootQuery },
    ]
  },
  {
    module: 'lib/hooks/useNavigationState',
    exports: [
      { name: 'useNavigationState', value: useNavigationState },
    ]
  },
  {
    module: 'src/components/authorable/shared/lists/ContextualNavItem',
    exports: [
      { name: 'ContextualNavItem', value: ContextualNavItem },
    ]
  },
  {
    module: '@splidejs/splide-extension-intersection',
    exports: [
      { name: 'Intersection', value: Intersection },
    ]
  },
  {
    module: '@splidejs/react-splide',
    exports: [
      { name: 'Splide', value: Splide },
      { name: 'SplideSlide', value: SplideSlide },
      { name: 'SplideTrack', value: SplideTrack },
    ]
  },
  {
    module: 'helpers/Context/AccordionContext',
    exports: [
      { name: 'useAccordionItemContext', value: useAccordionItemContext },
      { name: 'AccordionContextProvider', value: AccordionContextProvider },
      { name: 'useAccordionContext', value: useAccordionContext },
    ]
  },
  {
    module: 'lib/context/TextAlignmentContext',
    exports: [
      { name: 'TextAlignmentProvider', value: TextAlignmentProvider },
    ]
  },
  {
    module: 'helpers/Context/JumpNavContext',
    exports: [
      { name: 'useWatchJumpNavActiveState', value: useWatchJumpNavActiveState },
      { name: 'JumpNavContextProvider', value: JumpNavContextProvider },
      { name: 'useJumpNavContext', value: useJumpNavContext },
      { name: 'useMainHeaderHeight', value: useMainHeaderHeight },
    ]
  },
  {
    module: 'lib/utils/dom-utils/tab',
    exports: [
      { name: 'focusUnfocusableElement', value: focusUnfocusableElement },
    ]
  },
  {
    module: 'clsx',
    exports: [
      { name: 'default', value: clsx },
    ]
  },
  {
    module: 'helpers/GenericWrappers/ModalWrapper/ModalWrapper',
    exports: [
      { name: 'default', value: ModalWrapper },
    ]
  },
  {
    module: 'next/script',
    exports: [
      { name: 'default', value: Script },
    ]
  },
  {
    module: 'lib/utils/link-utils',
    exports: [
      { name: 'getScriptUrl', value: getScriptUrl },
    ]
  },
  {
    module: 'lib/hooks/useIsNormalMode',
    exports: [
      { name: 'default', value: useIsNormalMode },
    ]
  },
  {
    module: 'js-cookie',
    exports: [
      { name: 'default', value: Cookies },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
