---
ID: "c4b08e9a-49fd-449d-9319-94ec3f6b8e5c"
Parent: "a4b9562a-e740-4e54-9978-044da7f9d0bb"
Template: "a4b9562a-e740-4e54-9978-044da7f9d0bb"
Path: /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250519T152753Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\anandakumar.a@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\anandakumar.a@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3281d5e9-82d6-4b47-b1b5-6885c4931d3c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\anandakumar.a@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250519T152753Z
