
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Media.InlineVideo InlineVideo Media
// @ts-ignore
import { Media as MediaInlineVideoMedia } from "./InlineVideo.model"
// Template: Feature.HztlFoundation.Media.InlineVideo InlineVideo Folder Media
// Template: Media already imported
// Template: Feature.HztlFoundation.Media.InlineVideo InlineVideo Parameters Media
// Template: Media already imported

export namespace Media.InlineVideo {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo
    */
    export type InlineVideo =  {
        fields?: { 
            /**
            * Represents the Video Height field (2908b616-53bb-4c70-8aad-345cf018d044).
            */
            height?: Field<string>;

            /**
            * Represents the Title field (06757e01-1696-40f2-a39f-cfb888a055db).
            */
            title?: Field<string>;

            /**
            * Represents the Url field (047cd99b-7ef4-4410-9b00-42bb85277be5).
            */
            url?: Field<string>;

            /**
            * Represents the Video Width field (ce97a913-c4b8-44bd-aa60-b8910b5b7671).
            */
            width?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo as an Item
    */
    export type InlineVideo_Item = Omit<Item, 'fields'> & InlineVideo

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo as a Component
    */
    export type InlineVideo_Component = ComponentProps & InlineVideo

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo
    */
    export type InlineVideoJson =  {
        
            /**
            * Represents the Video Height field (2908b616-53bb-4c70-8aad-345cf018d044).
            */
            height?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Title field (06757e01-1696-40f2-a39f-cfb888a055db).
            */
            title?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Url field (047cd99b-7ef4-4410-9b00-42bb85277be5).
            */
            url?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Video Width field (ce97a913-c4b8-44bd-aa60-b8910b5b7671).
            */
            width?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo Folder
    */
    export type InlineVideoFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo Folder as an Item
    */
    export type InlineVideoFolder_Item = Omit<Item, 'fields'> & InlineVideoFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo Folder as a Component
    */
    export type InlineVideoFolder_Component = ComponentProps & InlineVideoFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo Folder
    */
    export type InlineVideoFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo Parameters
    */
    export type InlineVideoParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo Parameters as an Item
    */
    export type InlineVideoParameters_Item = Omit<Item, 'fields'> & InlineVideoParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo Parameters as a Component
    */
    export type InlineVideoParameters_Component = ComponentProps & InlineVideoParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Media/InlineVideo/InlineVideo Parameters
    */
    export type InlineVideoParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Media.InlineVideo.Constants {

    export const InlineVideo = {
        TemplateId: "5da29931-8225-44fb-bb4a-95a709fdd3ca",
    
        BaseTemplateIds: [
        ]
    }
    export const InlineVideoFolder = {
        TemplateId: "448910ae-0623-4221-888e-397b0dcfd793",
    
        BaseTemplateIds: [
        ]
    }
    export const InlineVideoParameters = {
        TemplateId: "c6f82986-4451-4b9e-b4c6-43c9a7eef1bd",
    
        BaseTemplateIds: [
        ]
    }
}    


