
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Media.InlineImage InlineImage Media
// @ts-ignore
import { Media as MediaInlineImageMedia } from "./InlineImage.model"
// Template: Feature.HztlFoundation.Media.InlineImage InlineImage Folder Media
// Template: Media already imported
// Template: Feature.HztlFoundation.Media.InlineImage InlineImage Parameters Media
// Template: Media already imported

export namespace Media.InlineImage {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage
    */
    export type InlineImage =  {
        fields?: { 
            /**
            * Represents the Image Caption field (7f66b1b7-983a-4d51-abfa-c72cad7b1573).
            */
            caption?: Field<string>;

            /**
            * Represents the Desktop Image field (d98afe98-9e8d-42af-95ee-f8a7da4a9711).
            */
            desktopImage?: ImageField;

            /**
            * Represents the Mobile Image field (702ce4b1-559c-46aa-9b03-a95841478c51).
            */
            mobileImage?: ImageField;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage as an Item
    */
    export type InlineImage_Item = Omit<Item, 'fields'> & InlineImage

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage as a Component
    */
    export type InlineImage_Component = ComponentProps & InlineImage

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage
    */
    export type InlineImageJson =  {
        
            /**
            * Represents the Image Caption field (7f66b1b7-983a-4d51-abfa-c72cad7b1573).
            */
            caption?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Desktop Image field (d98afe98-9e8d-42af-95ee-f8a7da4a9711).
            */
            desktopImage?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Mobile Image field (702ce4b1-559c-46aa-9b03-a95841478c51).
            */
            mobileImage?: {
                jsonValue: ImageField
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage Folder
    */
    export type InlineImageFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage Folder as an Item
    */
    export type InlineImageFolder_Item = Omit<Item, 'fields'> & InlineImageFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage Folder as a Component
    */
    export type InlineImageFolder_Component = ComponentProps & InlineImageFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage Folder
    */
    export type InlineImageFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage Parameters
    */
    export type InlineImageParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage Parameters as an Item
    */
    export type InlineImageParameters_Item = Omit<Item, 'fields'> & InlineImageParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage Parameters as a Component
    */
    export type InlineImageParameters_Component = ComponentProps & InlineImageParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Media/InlineImage/InlineImage Parameters
    */
    export type InlineImageParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Media.InlineImage.Constants {

    export const InlineImage = {
        TemplateId: "5c607db6-6ec9-4db3-bff5-7c2edd6523fb",
    
        BaseTemplateIds: [
        ]
    }
    export const InlineImageFolder = {
        TemplateId: "df36f8e6-ab13-4c04-8e6c-2f6ddeb15fc3",
    
        BaseTemplateIds: [
        ]
    }
    export const InlineImageParameters = {
        TemplateId: "a4b9562a-e740-4e54-9978-044da7f9d0bb",
    
        BaseTemplateIds: [
        ]
    }
}    


