
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Media.InlineIFrame Inline IFrame Folder Media
// @ts-ignore
import { Media as MediaInlineIFrameMedia } from "./InlineIFrame.model"
// Template: Feature.HztlFoundation.Media.InlineIFrame InlineIFrame Media
// Template: Media already imported
// Template: Feature.HztlFoundation.Media.InlineIFrame InlineIFrame Media
// Template: Media already imported

export namespace Media.InlineIFrame {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/Inline IFrame Folder
    */
    export type InlineIFrameFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/Inline IFrame Folder as an Item
    */
    export type InlineIFrameFolder_Item = Omit<Item, 'fields'> & InlineIFrameFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/Inline IFrame Folder as a Component
    */
    export type InlineIFrameFolder_Component = ComponentProps & InlineIFrameFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/Inline IFrame Folder
    */
    export type InlineIFrameFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/InlineIFrame
    */
    export type InlineIFrame =  {
        fields?: { 
            /**
            * Represents the __Standard Werte field (76fe9e7c-a5b4-4ca2-85a3-5ef1f00d4369).
            */
            embedUrl?: Field<string>;

            /**
            * Represents the Text field (61f191cb-903e-4e5e-a95b-0b26958032fc).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/InlineIFrame as an Item
    */
    export type InlineIFrame_Item = Omit<Item, 'fields'> & InlineIFrame

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/InlineIFrame as a Component
    */
    export type InlineIFrame_Component = ComponentProps & InlineIFrame

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/InlineIFrame
    */
    export type InlineIFrameJson =  {
        
            /**
            * Represents the __Standard Werte field (76fe9e7c-a5b4-4ca2-85a3-5ef1f00d4369).
            */
            embedUrl?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text field (61f191cb-903e-4e5e-a95b-0b26958032fc).
            */
            title?: {
                jsonValue: Field<string>
            };


    }
}
export namespace Media.InlineIFrame.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/Rendering Parameters/InlineIFrame
    */
    export type InlineIFrame =  {
        fields?: { 
            /**
            * Represents the Aspect Ratio field (a87e1e9e-2a67-4615-b7b4-16e890741794).
            */
            aspectRatio?: Field<string>;

            /**
            * Represents the Height field (d88c6933-4d9d-4ccc-a2f5-b8c075241c36).
            */
            height?: Field<string>;

            /**
            * Represents the Text 3 field (99bc2a6c-3160-4f78-b63a-ac7189610c88).
            */
            width?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/Rendering Parameters/InlineIFrame as an Item
    */
    export type InlineIFrame_Item = Omit<Item, 'fields'> & InlineIFrame

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/Rendering Parameters/InlineIFrame as a Component
    */
    export type InlineIFrame_Component = ComponentProps & InlineIFrame

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/Rendering Parameters/InlineIFrame
    */
    export type InlineIFrameJson =  {
        
            /**
            * Represents the Aspect Ratio field (a87e1e9e-2a67-4615-b7b4-16e890741794).
            */
            aspectRatio?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Height field (d88c6933-4d9d-4ccc-a2f5-b8c075241c36).
            */
            height?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text 3 field (99bc2a6c-3160-4f78-b63a-ac7189610c88).
            */
            width?: {
                jsonValue: Field<string>
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Media.InlineIFrame.Constants {

    export const InlineIFrameFolder = {
        TemplateId: "f401ef4a-e078-4e7c-aa96-1cf7736c882f",
    
        BaseTemplateIds: [
        ]
    }
    export const InlineIFrame = {
        TemplateId: "ad80926d-c860-4ad9-b07f-41a2b14a7b36",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Media.InlineIFrame.RenderingParameters.Constants {

    export const InlineIFrame = {
        TemplateId: "b52221d6-10ed-44e6-9a71-3eec9ef7eb15",
    
        BaseTemplateIds: [
        ]
    }
}    


