
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.SiteStructure.Breadcrumb Breadcrumb Parameters SiteStructure
// @ts-ignore
import { SiteStructure as SiteStructureBreadcrumbSiteStructure } from "./Breadcrumb.model"

export namespace SiteStructure.Breadcrumb {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Breadcrumb/Breadcrumb Parameters
    */
    export type BreadcrumbParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Breadcrumb/Breadcrumb Parameters as an Item
    */
    export type BreadcrumbParameters_Item = Omit<Item, 'fields'> & BreadcrumbParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Breadcrumb/Breadcrumb Parameters as a Component
    */
    export type BreadcrumbParameters_Component = ComponentProps & BreadcrumbParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Breadcrumb/Breadcrumb Parameters
    */
    export type BreadcrumbParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace SiteStructure.Breadcrumb.Constants {

    export const BreadcrumbParameters = {
        TemplateId: "621becbf-9a12-4a10-ba04-b2a0ecd6ca91",
    
        BaseTemplateIds: [
        ]
    }
}    


