
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.SiteStructure.Footer Footer SiteStructure
// @ts-ignore
import { SiteStructure as SiteStructureFooterSiteStructure } from "./Footer.model"
// Template: Feature.HztlFoundation.SiteStructure.Footer FooterColumn SiteStructure
// Template: SiteStructure already imported
// Template: Feature.HztlFoundation.SiteStructure.Footer Social Media Item SiteStructure
// Template: SiteStructure already imported
// Template: Feature.HztlFoundation.SiteStructure.Footer Social Media Item Folder SiteStructure
// Template: SiteStructure already imported

export namespace SiteStructure.Footer {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Footer
    */
    export type Footer =  {
        fields?: { 
            /**
            * Represents the Copyright (use token {{year}} for current year) field (351f41d7-3a14-4f63-9cc3-f06a10be3fcc).
            */
            copyrightText?: Field<string>;

            /**
            * Represents the Footer Columns field (fad6beb9-19f0-40b9-99bf-8d10903192f9).
            */
            footerColumns?: Item[];

            /**
            * Represents the Footer Description field (43cd77c9-dd9a-4701-80b3-702ea9f1ffed).
            */
            footerDescription?: Field<string>;

            /**
            * Represents the Footer Logo field (ee79b5c7-4f16-41e9-9db3-91df531562fd).
            */
            footerLogo?: ImageField;

            /**
            * Represents the Footer Logo Link field (956235fd-b64b-4689-9721-93a733de2225).
            */
            footerLogoLink?: LinkField;

            /**
            * Represents the Social Links field (232c2560-a480-46a8-bd23-dbcb38d2aedc).
            */
            socialMediaLinks?: Item[];
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Footer as an Item
    */
    export type Footer_Item = Omit<Item, 'fields'> & Footer

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Footer as a Component
    */
    export type Footer_Component = ComponentProps & Footer

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Footer
    */
    export type FooterJson =  {
        
            /**
            * Represents the Copyright (use token {{year}} for current year) field (351f41d7-3a14-4f63-9cc3-f06a10be3fcc).
            */
            copyrightText?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Footer Columns field (fad6beb9-19f0-40b9-99bf-8d10903192f9).
            */
            footerColumns?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Footer Description field (43cd77c9-dd9a-4701-80b3-702ea9f1ffed).
            */
            footerDescription?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Footer Logo field (ee79b5c7-4f16-41e9-9db3-91df531562fd).
            */
            footerLogo?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Footer Logo Link field (956235fd-b64b-4689-9721-93a733de2225).
            */
            footerLogoLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Social Links field (232c2560-a480-46a8-bd23-dbcb38d2aedc).
            */
            socialMediaLinks?: {
                jsonValue: Item[]
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/FooterColumn
    */
    export type FooterColumn =  {
        fields?: { 
            /**
            * Represents the Column Header field (9377ca2d-42cb-4a25-b4d8-1c1fdd6bf8c6).
            */
            columnHeader?: Field<string>;

            /**
            * Represents the Column Links field (e2ba8384-6ddd-4513-82ac-abd0e087c430).
            */
            columnLinks?: Item[];
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/FooterColumn as an Item
    */
    export type FooterColumn_Item = Omit<Item, 'fields'> & FooterColumn

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/FooterColumn as a Component
    */
    export type FooterColumn_Component = ComponentProps & FooterColumn

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/FooterColumn
    */
    export type FooterColumnJson =  {
        
            /**
            * Represents the Column Header field (9377ca2d-42cb-4a25-b4d8-1c1fdd6bf8c6).
            */
            columnHeader?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Column Links field (e2ba8384-6ddd-4513-82ac-abd0e087c430).
            */
            columnLinks?: {
                jsonValue: Item[]
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media Item
    */
    export type SocialMediaItem =  {
        fields?: { 
            /**
            * Represents the Social Media Link field (889296b7-cee2-4b50-b648-99c604288152).
            */
            socialMediaLink?: LinkField;

            /**
            * Represents the Social Media Logo field (5648e0e7-f035-48f5-aebe-296b8a096192).
            */
            socialMediaLogo?: ImageField;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media Item as an Item
    */
    export type SocialMediaItem_Item = Omit<Item, 'fields'> & SocialMediaItem

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media Item as a Component
    */
    export type SocialMediaItem_Component = ComponentProps & SocialMediaItem

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media Item
    */
    export type SocialMediaItemJson =  {
        
            /**
            * Represents the Social Media Link field (889296b7-cee2-4b50-b648-99c604288152).
            */
            socialMediaLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Social Media Logo field (5648e0e7-f035-48f5-aebe-296b8a096192).
            */
            socialMediaLogo?: {
                jsonValue: ImageField
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media Item Folder
    */
    export type SocialMediaItemFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media Item Folder as an Item
    */
    export type SocialMediaItemFolder_Item = Omit<Item, 'fields'> & SocialMediaItemFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media Item Folder as a Component
    */
    export type SocialMediaItemFolder_Component = ComponentProps & SocialMediaItemFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Footer/Social Media Item Folder
    */
    export type SocialMediaItemFolderJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace SiteStructure.Footer.Constants {

    export const Footer = {
        TemplateId: "39461909-13b3-4b3e-a306-2c01aa783f5e",
    
        BaseTemplateIds: [
        ]
    }
    export const FooterColumn = {
        TemplateId: "08d755a3-a6fa-4f8b-b574-414077d83a52",
    
        BaseTemplateIds: [
        ]
    }
    export const SocialMediaItem = {
        TemplateId: "5e1ae8e0-8f0c-443c-ac85-144f1e47e4af",
    
        BaseTemplateIds: [
        ]
    }
    export const SocialMediaItemFolder = {
        TemplateId: "b05f1a98-eec9-4c0b-b29a-e4d1235f06d8",
    
        BaseTemplateIds: [
        ]
    }
}    


