
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.SiteStructure.Header Header SiteStructure
// @ts-ignore
import { SiteStructure as SiteStructureHeaderSiteStructure } from "./Header.model"
// Template: Feature.HztlFoundation.SiteStructure.Header Mega Menu Group SiteStructure
// Template: SiteStructure already imported
// Template: Feature.HztlFoundation.SiteStructure.Header Navigation Group SiteStructure
// Template: SiteStructure already imported
// Template: Feature.HztlFoundation.SiteStructure.Header Region SiteStructure
// Template: SiteStructure already imported
// Template: Feature.HztlFoundation.SiteStructure.Header Region Folder SiteStructure
// Template: SiteStructure already imported

export namespace SiteStructure.Header {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Header
    */
    export type Header =  {
        fields?: { 
            /**
            * Represents the Logo field (ca3d785b-2bc3-41f3-a528-70d0c709ec89).
            */
            logo?: ImageField;

            /**
            * Represents the Logo Link field (35d83a50-8086-48e8-88a0-63cdbd4a6bdf).
            */
            logoLink?: LinkField;

            /**
            * Represents the Navigation List field (d250b2fd-502b-423b-b355-b0a067345f7c).
            */
            navigationList?: Item[];

            /**
            * Represents the Region List field (c1dc367b-124f-41ec-b3cd-24e5a8cd7e71).
            */
            regionList?: Item[];

            /**
            * Represents the Search Placeholder field (8e132bdc-18c7-4b27-931f-49c201efef52).
            */
            searchPlaceholder?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Header as an Item
    */
    export type Header_Item = Omit<Item, 'fields'> & Header

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Header as a Component
    */
    export type Header_Component = ComponentProps & Header

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Header
    */
    export type HeaderJson =  {
        
            /**
            * Represents the Logo field (ca3d785b-2bc3-41f3-a528-70d0c709ec89).
            */
            logo?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Logo Link field (35d83a50-8086-48e8-88a0-63cdbd4a6bdf).
            */
            logoLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Navigation List field (d250b2fd-502b-423b-b355-b0a067345f7c).
            */
            navigationList?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Region List field (c1dc367b-124f-41ec-b3cd-24e5a8cd7e71).
            */
            regionList?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Search Placeholder field (8e132bdc-18c7-4b27-931f-49c201efef52).
            */
            searchPlaceholder?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Mega Menu Group
    */
    export type MegaMenuGroup =  {
        fields?: { 
            /**
            * Represents the Mega Menu CTA (Link text will be always 'View All' from the Dictionary) field (d05ad53b-2c0e-425c-8e62-49b14f8afc6d).
            */
            megaMenuCTA?: LinkField;

            /**
            * Represents the Mega Menu Links field (b4a35c51-f674-4101-821d-e6069590013d).
            */
            megaMenuLinks?: Item[];

            /**
            * Represents the Mega Menu Title field (2f52f5ae-00bd-46ee-804b-4505a60984fc).
            */
            megaMenuTitle?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Mega Menu Group as an Item
    */
    export type MegaMenuGroup_Item = Omit<Item, 'fields'> & MegaMenuGroup

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Mega Menu Group as a Component
    */
    export type MegaMenuGroup_Component = ComponentProps & MegaMenuGroup

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Mega Menu Group
    */
    export type MegaMenuGroupJson =  {
        
            /**
            * Represents the Mega Menu CTA (Link text will be always 'View All' from the Dictionary) field (d05ad53b-2c0e-425c-8e62-49b14f8afc6d).
            */
            megaMenuCTA?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Mega Menu Links field (b4a35c51-f674-4101-821d-e6069590013d).
            */
            megaMenuLinks?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Mega Menu Title field (2f52f5ae-00bd-46ee-804b-4505a60984fc).
            */
            megaMenuTitle?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Navigation Group
    */
    export type NavigationGroup =  {
        fields?: { 
            /**
            * Represents the Feature Description field (6ffbc892-e4af-4b54-b477-162b2b0ed777).
            */
            featureDescription?: Field<string>;

            /**
            * Represents the Feature Image field (a0cb6376-9360-4fa9-97ac-f20b3d4264ef).
            */
            featureImage?: ImageField;

            /**
            * Represents the Feature Title field (b0624b6e-16a1-4a22-bb2d-747224d952fd).
            */
            featureTitle?: Field<string>;

            /**
            * Represents the Mega Menu List field (0a0188a9-97df-4022-afe5-6aa703e207b5).
            */
            megaMenuList?: Item[];

            /**
            * Represents the Navigation Link field (23bf11d2-b48b-4e45-a721-c16dedd7f034).
            */
            navigationLink?: LinkField;

            /**
            * Represents the Navigation Title field (a1f1758f-eb43-4a9f-8f67-7ec880210d6e).
            */
            navigationTitle?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Navigation Group as an Item
    */
    export type NavigationGroup_Item = Omit<Item, 'fields'> & NavigationGroup

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Navigation Group as a Component
    */
    export type NavigationGroup_Component = ComponentProps & NavigationGroup

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Navigation Group
    */
    export type NavigationGroupJson =  {
        
            /**
            * Represents the Feature Description field (6ffbc892-e4af-4b54-b477-162b2b0ed777).
            */
            featureDescription?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Feature Image field (a0cb6376-9360-4fa9-97ac-f20b3d4264ef).
            */
            featureImage?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Feature Title field (b0624b6e-16a1-4a22-bb2d-747224d952fd).
            */
            featureTitle?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Mega Menu List field (0a0188a9-97df-4022-afe5-6aa703e207b5).
            */
            megaMenuList?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Navigation Link field (23bf11d2-b48b-4e45-a721-c16dedd7f034).
            */
            navigationLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Navigation Title field (a1f1758f-eb43-4a9f-8f67-7ec880210d6e).
            */
            navigationTitle?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Region
    */
    export type Region =  {
        fields?: { 
            /**
            * Represents the Language List field (cc70f167-0aa2-408d-97cf-233cb68c9deb).
            */
            languageList?: Item[];

            /**
            * Represents the Region Name field (1f11d5bc-bc32-4e60-a314-9f6a81d40c0e).
            */
            regionName?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Region as an Item
    */
    export type Region_Item = Omit<Item, 'fields'> & Region

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Region as a Component
    */
    export type Region_Component = ComponentProps & Region

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Region
    */
    export type RegionJson =  {
        
            /**
            * Represents the Language List field (cc70f167-0aa2-408d-97cf-233cb68c9deb).
            */
            languageList?: {
                jsonValue: Item[]
            };

            /**
            * Represents the Region Name field (1f11d5bc-bc32-4e60-a314-9f6a81d40c0e).
            */
            regionName?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Region Folder
    */
    export type RegionFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Region Folder as an Item
    */
    export type RegionFolder_Item = Omit<Item, 'fields'> & RegionFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Region Folder as a Component
    */
    export type RegionFolder_Component = ComponentProps & RegionFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/Header/Region Folder
    */
    export type RegionFolderJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace SiteStructure.Header.Constants {

    export const Header = {
        TemplateId: "fe3931aa-09c3-4b59-b08b-96d1003c3e78",
    
        BaseTemplateIds: [
        ]
    }
    export const MegaMenuGroup = {
        TemplateId: "a7c5aa3a-f9f5-4a91-821a-6c519b481628",
    
        BaseTemplateIds: [
        ]
    }
    export const NavigationGroup = {
        TemplateId: "7b95a120-283b-474a-a839-6e06409c23a9",
    
        BaseTemplateIds: [
        ]
    }
    export const Region = {
        TemplateId: "a61c3806-a1dc-4f4f-8644-07f3b663fd2a",
    
        BaseTemplateIds: [
        ]
    }
    export const RegionFolder = {
        TemplateId: "8632a048-536c-4293-bf80-424662c78ca6",
    
        BaseTemplateIds: [
        ]
    }
}    


