
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.SiteStructure.MainLayout MainLayout Parameters SiteStructure
// @ts-ignore
import { SiteStructure as SiteStructureMainLayoutSiteStructure } from "./MainLayout.model"

export namespace SiteStructure.MainLayout {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/MainLayout/MainLayout Parameters
    */
    export type MainLayoutParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/MainLayout/MainLayout Parameters as an Item
    */
    export type MainLayoutParameters_Item = Omit<Item, 'fields'> & MainLayoutParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/MainLayout/MainLayout Parameters as a Component
    */
    export type MainLayoutParameters_Component = ComponentProps & MainLayoutParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/MainLayout/MainLayout Parameters
    */
    export type MainLayoutParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace SiteStructure.MainLayout.Constants {

    export const MainLayoutParameters = {
        TemplateId: "6413fe87-e29d-4ee6-a4ef-d1a5c659a2b1",
    
        BaseTemplateIds: [
        ]
    }
}    


