
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.SiteStructure.SkipNav SkipNav Parameters SiteStructure
// @ts-ignore
import { SiteStructure as SiteStructureSkipNavSiteStructure } from "./SkipNav.model"

export namespace SiteStructure.SkipNav {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/SkipNav/SkipNav Parameters
    */
    export type SkipNavParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/SkipNav/SkipNav Parameters as an Item
    */
    export type SkipNavParameters_Item = Omit<Item, 'fields'> & SkipNavParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/SiteStructure/SkipNav/SkipNav Parameters as a Component
    */
    export type SkipNavParameters_Component = ComponentProps & SkipNavParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/SiteStructure/SkipNav/SkipNav Parameters
    */
    export type SkipNavParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace SiteStructure.SkipNav.Constants {

    export const SkipNavParameters = {
        TemplateId: "3dae105a-2ca9-43f5-a44c-79ce2a1c557d",
    
        BaseTemplateIds: [
        ]
    }
}    


