// Global
import type { Meta, StoryObj } from '@storybook/react';

// Local
import { CardItemProps, Default } from 'components/authorable/shared/lists/CardItem';
import { expandObj, flattenObj } from 'lib/object-parser';
import defaultData from 'stories/components/authorable/shared/lists/CardItem/CardItem.mock-data';

const meta: Meta<typeof Default> = {
  argTypes: {
    'fields.cardImage.value.alt': {
      table: {
        category: 'fields',
      },
    },
    'fields.cardImage.value.src': {
      table: {
        category: 'fields',
      },
    },
    'fields.cardImage.value.title': {
      table: {
        category: 'fields',
      },
    },
    'fields.cardLink1.value.href': {
      table: {
        category: 'fields',
      },
    },
    'fields.cardLink1.value.linktype': {
      table: {
        category: 'fields',
      },
    },
    'fields.cardLink1.value.target': {
      table: {
        category: 'fields',
      },
    },
    'fields.cardLink1.value.text': {
      table: {
        category: 'fields',
      },
    },
    'fields.cardLink2.value.href': {
      table: {
        category: 'fields',
      },
    },
    'fields.cardLink2.value.linktype': {
      table: {
        category: 'fields',
      },
    },
    'fields.cardLink2.value.target': {
      table: {
        category: 'fields',
      },
    },
    'fields.cardLink2.value.text': {
      table: {
        category: 'fields',
      },
    },
    'fields.description.value': {
      table: {
        category: 'fields',
      },
    },
    'fields.eyebrow.value': {
      table: {
        category: 'fields',
      },
    },
    'fields.heading.value': {
      table: {
        category: 'fields',
      },
    },
    'fields.subHeading.value': {
      table: {
        category: 'fields',
      },
    },
    'params.DynamicPlaceholderId': {
      table: {
        category: 'params',
      },
    },
    'params.FieldNames': {
      table: {
        category: 'params',
      },
    },
    'params.GridParameters': {
      table: {
        category: 'params',
      },
    },
    'params.Styles': {
      table: {
        category: 'params',
      },
    },
    'rendering.componentName': {
      table: {
        category: 'rendering',
      },
    },
    'rendering.dataSource': {
      table: {
        category: 'rendering',
      },
    },
    uid: {
      description:
        "A unique ID generated by Sitecore that will serve as the basis for the modal's ID attribute.",
    },
    /* eslint-disable  @typescript-eslint/no-explicit-any */
  } as any,
  component: Default,
  decorators: [
    (Story) => (
      <ul className="gap-6 grid grid-cols-none px-4 lg:grid-cols-1">
        <li className="flex flex-col gap-4">
          <Story />
        </li>
      </ul>
    ),
  ],
  parameters: {
    docs: {
      description: {
        component: `
## Overview
The Card component is a flexible container that groups related content and actions about a single subject. It often includes elements like images, text, buttons, and other interactive components, making it ideal for displaying concise, visually appealing information.

## Usage
The Card component is perfect for scenarios where you need to display summarized content with actionable elements. Common use cases include:
- **Showcasing Products or Services:** Highlight features or offerings with relevant CTAs.
- **Content Previews:** Provide summaries of articles, blogs, or news items.
- **User Profiles or Testimonials:** Present compact information about individuals or customer feedback.

### Key Features:

- **Image Support:** Display a featured image with customizable alt text and title for better accessibility and SEO.
- **Content Blocks:** Includes fields for a headline, subheading, description, and optional eyebrow text to structure information effectively.
- **CTAs:** Supports two configurable buttons (primary and secondary) to drive user actions.
- **Customizable Layouts:** Parameters for grid styling and custom styles allow seamless integration with any design.

### Configuration:

To configure the Card component, use the following fields and parameters:

- **fields.cardImage.value:** Set the source, alt text, and title of the featured image.
- **fields.heading.value:** Provide the main title of the card.
- **fields.subHeading.value:** Include an optional subtitle for additional context.
- **fields.description.value:** Add a brief description or summary of the content.
- **fields.cardLink1.value:** Define the primary button's text, URL, and attributes.
- **fields.cardLink2.value:** Configure a secondary button with similar options.
- **params.GridParameters:** Adjust grid layouts for the card container.
- **params.Styles:** Apply custom styles to the card for design consistency.`,
      },
    },
  },
  title: 'Components/Authorable/Shared/Lists/Card Item',
};

export default meta;

type Story = StoryObj<typeof Default>;

export const Card: Story = {
  args: {
    ...flattenObj(defaultData),
  },
  name: 'Default',
  render: (args) => {
    return <Default {...(expandObj({ ...args }) as CardItemProps)} />;
  },
};
