---
ID: "e59217b3-435d-42f0-a8ff-90584bede23e"
Parent: "944cf68e-51e3-43f2-b521-273b1d007589"
Template: "944cf68e-51e3-43f2-b521-273b1d007589"
Path: /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Center 75 Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "44ae7150-10e2-429d-ab99-fb6f27a560ce"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\anandakumar.a@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250710T141120Z
