
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Lists.Accordion Accordion Parameters Lists
// @ts-ignore
import { Lists as ListsAccordionLists } from "./Accordion.model"
// Template: Feature.HztlFoundation.Lists.Accordion AccordionItem Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.Accordion AccordionItem Folder Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.Accordion AccordionItem Parameters Lists
// Template: Lists already imported

export namespace Lists.Accordion {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/Accordion Parameters
    */
    export type AccordionParameters =  {
        fields?: { 
            /**
            * Represents the Open By Default field (046938a1-9167-48cb-80ed-e998cf176b5c).
            */
            openByDefault?: Field<boolean>;

            /**
            * Represents the Scroll To Open Panel field (ab57a06a-793d-4b33-bf59-2d0e92ae76e0).
            */
            scrollToOpenPanel?: Field<boolean>;

            /**
            * Represents the Only Allow 1 Open Panel field (228ce8c6-03e5-4aa6-9874-c3bd39aebcd0).
            */
            singleOpenPanel?: Field<boolean>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/Accordion Parameters as an Item
    */
    export type AccordionParameters_Item = Omit<Item, 'fields'> & AccordionParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/Accordion Parameters as a Component
    */
    export type AccordionParameters_Component = ComponentProps & AccordionParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/Accordion Parameters
    */
    export type AccordionParametersJson =  {
        
            /**
            * Represents the Open By Default field (046938a1-9167-48cb-80ed-e998cf176b5c).
            */
            openByDefault?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Scroll To Open Panel field (ab57a06a-793d-4b33-bf59-2d0e92ae76e0).
            */
            scrollToOpenPanel?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Only Allow 1 Open Panel field (228ce8c6-03e5-4aa6-9874-c3bd39aebcd0).
            */
            singleOpenPanel?: {
                jsonValue: Field<boolean>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem
    */
    export type AccordionItem =  {
        fields?: { 
            /**
            * Represents the Content field (910b7376-fd3a-447a-8c38-f982811e6084).
            */
            content?: Field<string>;

            /**
            * Represents the Heading field (7002c7ba-11c5-4bb8-ba2e-6f1c4ff2a750).
            */
            heading?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem as an Item
    */
    export type AccordionItem_Item = Omit<Item, 'fields'> & AccordionItem

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem as a Component
    */
    export type AccordionItem_Component = ComponentProps & AccordionItem

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem
    */
    export type AccordionItemJson =  {
        
            /**
            * Represents the Content field (910b7376-fd3a-447a-8c38-f982811e6084).
            */
            content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Heading field (7002c7ba-11c5-4bb8-ba2e-6f1c4ff2a750).
            */
            heading?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem Folder
    */
    export type AccordionItemFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem Folder as an Item
    */
    export type AccordionItemFolder_Item = Omit<Item, 'fields'> & AccordionItemFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem Folder as a Component
    */
    export type AccordionItemFolder_Component = ComponentProps & AccordionItemFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem Folder
    */
    export type AccordionItemFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem Parameters
    */
    export type AccordionItemParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem Parameters as an Item
    */
    export type AccordionItemParameters_Item = Omit<Item, 'fields'> & AccordionItemParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem Parameters as a Component
    */
    export type AccordionItemParameters_Component = ComponentProps & AccordionItemParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Accordion/AccordionItem Parameters
    */
    export type AccordionItemParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Lists.Accordion.Constants {

    export const AccordionParameters = {
        TemplateId: "7a436cb9-473e-4270-99b3-d301964d7689",
    
        BaseTemplateIds: [
        ]
    }
    export const AccordionItem = {
        TemplateId: "22298e17-88e2-46ad-85a8-aa8b77434bf2",
    
        BaseTemplateIds: [
        ]
    }
    export const AccordionItemFolder = {
        TemplateId: "6e7c7004-0d73-40e9-82ea-2f14d09db64f",
    
        BaseTemplateIds: [
        ]
    }
    export const AccordionItemParameters = {
        TemplateId: "82b8c484-3e95-437f-92bb-f58ef08c2684",
    
        BaseTemplateIds: [
        ]
    }
}    


