
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Lists.CardList CardItem Lists
// @ts-ignore
import { Lists as ListsCardListLists } from "./CardList.model"
// Template: Feature.HztlFoundation.Lists.CardList CardItem Folder Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.CardList CardItem Parameters Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.CardList CardList Parameters Lists
// Template: Lists already imported

export namespace Lists.CardList {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem
    */
    export type CardItem =  {
        fields?: { 
            /**
            * Represents the Text field (d7b576b3-7bea-46e6-bb0a-49edb06481d7).
            */
            cardImage?: ImageField;

            /**
            * Represents the cardLink1 field (c9d402e1-0e1c-4b9b-9f72-0c66f4249145).
            */
            cardLink1?: LinkField;

            /**
            * Represents the cardLink2 field (ebf65880-3433-4f9c-82fe-33400ef39565).
            */
            cardLink2?: LinkField;

            /**
            * Represents the description field (06cc0659-30f3-4acd-8d70-acd3b71a021e).
            */
            description?: Field<string>;

            /**
            * Represents the eyebrow field (2bf4e3c9-4548-48cc-90dc-bac4db7d054f).
            */
            eyebrow?: Field<string>;

            /**
            * Represents the heading field (e12882dc-a694-483c-a1f7-2917c96cdd5a).
            */
            heading?: Field<string>;

            /**
            * Represents the subHeading field (dbd8adc9-d5d2-45d7-a093-a74deaf084d0).
            */
            subHeading?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem as an Item
    */
    export type CardItem_Item = Omit<Item, 'fields'> & CardItem

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem as a Component
    */
    export type CardItem_Component = ComponentProps & CardItem

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem
    */
    export type CardItemJson =  {
        
            /**
            * Represents the Text field (d7b576b3-7bea-46e6-bb0a-49edb06481d7).
            */
            cardImage?: {
                jsonValue: ImageField
            };

            /**
            * Represents the cardLink1 field (c9d402e1-0e1c-4b9b-9f72-0c66f4249145).
            */
            cardLink1?: {
                jsonValue: LinkField
            };

            /**
            * Represents the cardLink2 field (ebf65880-3433-4f9c-82fe-33400ef39565).
            */
            cardLink2?: {
                jsonValue: LinkField
            };

            /**
            * Represents the description field (06cc0659-30f3-4acd-8d70-acd3b71a021e).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the eyebrow field (2bf4e3c9-4548-48cc-90dc-bac4db7d054f).
            */
            eyebrow?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the heading field (e12882dc-a694-483c-a1f7-2917c96cdd5a).
            */
            heading?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the subHeading field (dbd8adc9-d5d2-45d7-a093-a74deaf084d0).
            */
            subHeading?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem Folder
    */
    export type CardItemFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem Folder as an Item
    */
    export type CardItemFolder_Item = Omit<Item, 'fields'> & CardItemFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem Folder as a Component
    */
    export type CardItemFolder_Component = ComponentProps & CardItemFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem Folder
    */
    export type CardItemFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem Parameters
    */
    export type CardItemParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem Parameters as an Item
    */
    export type CardItemParameters_Item = Omit<Item, 'fields'> & CardItemParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem Parameters as a Component
    */
    export type CardItemParameters_Component = ComponentProps & CardItemParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardItem Parameters
    */
    export type CardItemParametersJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardList Parameters
    */
    export type CardListParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardList Parameters as an Item
    */
    export type CardListParameters_Item = Omit<Item, 'fields'> & CardListParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardList Parameters as a Component
    */
    export type CardListParameters_Component = ComponentProps & CardListParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/CardList/CardList Parameters
    */
    export type CardListParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Lists.CardList.Constants {

    export const CardItem = {
        TemplateId: "3a7d27e5-b935-46da-b8fb-fe1e260957d8",
    
        BaseTemplateIds: [
        ]
    }
    export const CardItemFolder = {
        TemplateId: "315c2094-ebe1-45d3-b7f6-c57fec3d057c",
    
        BaseTemplateIds: [
        ]
    }
    export const CardItemParameters = {
        TemplateId: "c3ed0731-9d2b-4ec8-9494-760921cadd37",
    
        BaseTemplateIds: [
        ]
    }
    export const CardListParameters = {
        TemplateId: "49561e14-e1dd-4b06-b8e0-beaf908016c7",
    
        BaseTemplateIds: [
        ]
    }
}    


