
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Lists.Carousel Carousel Parameters Lists
// @ts-ignore
import { Lists as ListsCarouselLists } from "./Carousel.model"
// Template: Feature.HztlFoundation.Lists.Carousel CarouselItem Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.Carousel CarouselItem Folder Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.Carousel CarouselItem Parameters Lists
// Template: Lists already imported

export namespace Lists.Carousel {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/Carousel Parameters
    */
    export type CarouselParameters =  {
        fields?: { 
            /**
            * Represents the Auto Loop field (40ccdc74-269d-4590-ba85-ec94aa13350c).
            */
            autoLoop?: Field<boolean>;

            /**
            * Represents the Auto Play field (c26a0d3b-072f-45de-b47f-9bf4a3d6abdb).
            */
            autoPlay?: Field<boolean>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/Carousel Parameters as an Item
    */
    export type CarouselParameters_Item = Omit<Item, 'fields'> & CarouselParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/Carousel Parameters as a Component
    */
    export type CarouselParameters_Component = ComponentProps & CarouselParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/Carousel Parameters
    */
    export type CarouselParametersJson =  {
        
            /**
            * Represents the Auto Loop field (40ccdc74-269d-4590-ba85-ec94aa13350c).
            */
            autoLoop?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Auto Play field (c26a0d3b-072f-45de-b47f-9bf4a3d6abdb).
            */
            autoPlay?: {
                jsonValue: Field<boolean>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem
    */
    export type CarouselItem =  {
        fields?: { 
            /**
            * Represents the Description field (b07416fc-a4ad-409c-aee0-ce9a3738ac25).
            */
            description?: Field<string>;

            /**
            * Represents the Image field (fe5c4981-4e9d-4d1c-8c33-969f4a24badb).
            */
            image?: ImageField;

            /**
            * Represents the Primary CTA field (298e7b0d-fa2f-40ec-8ccc-4d9a6da34ae9).
            */
            primaryCTA?: LinkField;

            /**
            * Represents the Secondary CTA field (94f16d95-4102-4898-b7c3-71e1652b00c6).
            */
            secondaryCTA?: LinkField;

            /**
            * Represents the Title field (6e6c78dc-d4fc-472f-b29f-75a0498b8632).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem as an Item
    */
    export type CarouselItem_Item = Omit<Item, 'fields'> & CarouselItem

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem as a Component
    */
    export type CarouselItem_Component = ComponentProps & CarouselItem

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem
    */
    export type CarouselItemJson =  {
        
            /**
            * Represents the Description field (b07416fc-a4ad-409c-aee0-ce9a3738ac25).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Image field (fe5c4981-4e9d-4d1c-8c33-969f4a24badb).
            */
            image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Primary CTA field (298e7b0d-fa2f-40ec-8ccc-4d9a6da34ae9).
            */
            primaryCTA?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Secondary CTA field (94f16d95-4102-4898-b7c3-71e1652b00c6).
            */
            secondaryCTA?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Title field (6e6c78dc-d4fc-472f-b29f-75a0498b8632).
            */
            title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem Folder
    */
    export type CarouselItemFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem Folder as an Item
    */
    export type CarouselItemFolder_Item = Omit<Item, 'fields'> & CarouselItemFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem Folder as a Component
    */
    export type CarouselItemFolder_Component = ComponentProps & CarouselItemFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem Folder
    */
    export type CarouselItemFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem Parameters
    */
    export type CarouselItemParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem Parameters as an Item
    */
    export type CarouselItemParameters_Item = Omit<Item, 'fields'> & CarouselItemParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem Parameters as a Component
    */
    export type CarouselItemParameters_Component = ComponentProps & CarouselItemParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Carousel/CarouselItem Parameters
    */
    export type CarouselItemParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Lists.Carousel.Constants {

    export const CarouselParameters = {
        TemplateId: "e934c35a-965e-4e8a-9555-e846a910368b",
    
        BaseTemplateIds: [
        ]
    }
    export const CarouselItem = {
        TemplateId: "2c75ef66-7cd8-43c4-90e2-ef4e44e337a9",
    
        BaseTemplateIds: [
        ]
    }
    export const CarouselItemFolder = {
        TemplateId: "347730f0-15bd-4c30-a39d-9d7e42f1601e",
    
        BaseTemplateIds: [
        ]
    }
    export const CarouselItemParameters = {
        TemplateId: "dcea063a-de0e-408d-b98d-7c820e7f4238",
    
        BaseTemplateIds: [
        ]
    }
}    


