
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Lists.ContextualNav ContextualNav Parameters Lists
// @ts-ignore
import { Lists as ListsContextualNavLists } from "./ContextualNav.model"

export namespace Lists.ContextualNav {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/ContextualNav/ContextualNav Parameters
    */
    export type ContextualNavParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/ContextualNav/ContextualNav Parameters as an Item
    */
    export type ContextualNavParameters_Item = Omit<Item, 'fields'> & ContextualNavParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/ContextualNav/ContextualNav Parameters as a Component
    */
    export type ContextualNavParameters_Component = ComponentProps & ContextualNavParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/ContextualNav/ContextualNav Parameters
    */
    export type ContextualNavParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Lists.ContextualNav.Constants {

    export const ContextualNavParameters = {
        TemplateId: "e4e72a96-c4c3-4d07-b253-f59659e638f8",
    
        BaseTemplateIds: [
        ]
    }
}    


