
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Lists.FileList FileList Lists
// @ts-ignore
import { Lists as ListsFileListLists } from "./FileList.model"
// Template: Feature.HztlFoundation.Lists.FileList FileList Folder Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.FileList FileList Parameters Lists
// Template: Lists already imported
// Template: Foundation.HztlFoundation _Theme Base
// @ts-ignore
import { Base as FoundationHztlFoundationBase } from "./HztlFoundation.model"

export namespace Lists.FileList {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList
    */
    export type FileList =  {
        fields?: { 
            /**
            * Represents the CTA Link field (a4735976-57ea-4eb2-bf13-e574ac6d952d).
            */
            ctaLink?: LinkField;

            /**
            * Represents the Description field (735a42cb-8687-4c59-9a45-62114b2ceff8).
            */
            description?: Field<string>;

            /**
            * Represents the Headline field (1593aafa-5ea3-4061-bd0e-1d4973f51cba).
            */
            headline?: Field<string>;

            /**
            * Represents the Select Files field (8daf86c0-4f88-4262-a2bc-e866f7c97270).
            */
            selectFiles?: Item[];
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList as an Item
    */
    export type FileList_Item = Omit<Item, 'fields'> & FileList

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList as a Component
    */
    export type FileList_Component = ComponentProps & FileList

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList
    */
    export type FileListJson =  {
        
            /**
            * Represents the CTA Link field (a4735976-57ea-4eb2-bf13-e574ac6d952d).
            */
            ctaLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Description field (735a42cb-8687-4c59-9a45-62114b2ceff8).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Headline field (1593aafa-5ea3-4061-bd0e-1d4973f51cba).
            */
            headline?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Select Files field (8daf86c0-4f88-4262-a2bc-e866f7c97270).
            */
            selectFiles?: {
                jsonValue: Item[]
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList Folder
    */
    export type FileListFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList Folder as an Item
    */
    export type FileListFolder_Item = Omit<Item, 'fields'> & FileListFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList Folder as a Component
    */
    export type FileListFolder_Component = ComponentProps & FileListFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList Folder
    */
    export type FileListFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList Parameters
    */
    export type FileListParameters = FoundationHztlFoundationBase.Theme &  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList Parameters as an Item
    */
    export type FileListParameters_Item = Omit<Item, 'fields'> & FileListParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList Parameters as a Component
    */
    export type FileListParameters_Component = ComponentProps & FileListParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/FileList/FileList Parameters
    */
    export type FileListParametersJson = FoundationHztlFoundationBase.ThemeJson &  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Lists.FileList.Constants {

    export const FileList = {
        TemplateId: "02a305ae-cd14-42e4-9f2a-e58ea368a98c",
    
        BaseTemplateIds: [
        ]
    }
    export const FileListFolder = {
        TemplateId: "5caade0c-19a5-4188-b78b-2a1d951649d5",
    
        BaseTemplateIds: [
        ]
    }
    export const FileListParameters = {
        TemplateId: "7dcfd597-6dc5-427d-b60b-45621f10366b",
    
        BaseTemplateIds: [
            "2d5e2037-3132-4bcf-8654-79d99111292e", 
        ]
    }
}    


