
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Lists.Stats Stats Parameters Lists
// @ts-ignore
import { Lists as ListsStatsLists } from "./Stats.model"
// Template: Feature.HztlFoundation.Lists.Stats StatsItem Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.Stats StatsItem Folder Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.Stats StatsItem Parameters Lists
// Template: Lists already imported

export namespace Lists.Stats {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/Stats Parameters
    */
    export type StatsParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/Stats Parameters as an Item
    */
    export type StatsParameters_Item = Omit<Item, 'fields'> & StatsParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/Stats Parameters as a Component
    */
    export type StatsParameters_Component = ComponentProps & StatsParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/Stats Parameters
    */
    export type StatsParametersJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem
    */
    export type StatsItem =  {
        fields?: { 
            /**
            * Represents the Eyebrow field (9f299168-d6e8-4986-9cc2-dfbc9b40d87d).
            */
            eyebrow?: Field<string>;

            /**
            * Represents the Label field (42026964-d311-40e8-83e0-558d5bbbe2ba).
            */
            label?: Field<string>;

            /**
            * Represents the Number field (dc61c614-2f58-4a86-a01d-8489fd182517).
            */
            number?: Field<number>;

            /**
            * Represents the Interval/Quantifier field (a90a34a1-1ca8-467e-b23a-60ee667b0c32).
            */
            quantifier?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem as an Item
    */
    export type StatsItem_Item = Omit<Item, 'fields'> & StatsItem

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem as a Component
    */
    export type StatsItem_Component = ComponentProps & StatsItem

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem
    */
    export type StatsItemJson =  {
        
            /**
            * Represents the Eyebrow field (9f299168-d6e8-4986-9cc2-dfbc9b40d87d).
            */
            eyebrow?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Label field (42026964-d311-40e8-83e0-558d5bbbe2ba).
            */
            label?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Number field (dc61c614-2f58-4a86-a01d-8489fd182517).
            */
            number?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Interval/Quantifier field (a90a34a1-1ca8-467e-b23a-60ee667b0c32).
            */
            quantifier?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem Folder
    */
    export type StatsItemFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem Folder as an Item
    */
    export type StatsItemFolder_Item = Omit<Item, 'fields'> & StatsItemFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem Folder as a Component
    */
    export type StatsItemFolder_Component = ComponentProps & StatsItemFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem Folder
    */
    export type StatsItemFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem Parameters
    */
    export type StatsItemParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem Parameters as an Item
    */
    export type StatsItemParameters_Item = Omit<Item, 'fields'> & StatsItemParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem Parameters as a Component
    */
    export type StatsItemParameters_Component = ComponentProps & StatsItemParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Stats/StatsItem Parameters
    */
    export type StatsItemParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Lists.Stats.Constants {

    export const StatsParameters = {
        TemplateId: "c8ac2663-b9f8-4302-8c4b-588d971b0201",
    
        BaseTemplateIds: [
        ]
    }
    export const StatsItem = {
        TemplateId: "9c6b3f49-96bc-48d2-92dd-c918acf54a37",
    
        BaseTemplateIds: [
        ]
    }
    export const StatsItemFolder = {
        TemplateId: "603fb752-9061-4d36-b799-ec0c1a10d5dd",
    
        BaseTemplateIds: [
        ]
    }
    export const StatsItemParameters = {
        TemplateId: "0b384d8e-9641-412f-97c1-0e3b96898543",
    
        BaseTemplateIds: [
        ]
    }
}    


