
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Lists.Tab Tab Parameters Lists
// @ts-ignore
import { Lists as ListsTabLists } from "./Tab.model"
// Template: Feature.HztlFoundation.Lists.Tab TabItem Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.Tab TabItem Folder Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.Tab TabItem Parameters Lists
// Template: Lists already imported

export namespace Lists.Tab {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/Tab Parameters
    */
    export type TabParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/Tab Parameters as an Item
    */
    export type TabParameters_Item = Omit<Item, 'fields'> & TabParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/Tab Parameters as a Component
    */
    export type TabParameters_Component = ComponentProps & TabParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/Tab Parameters
    */
    export type TabParametersJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem
    */
    export type TabItem =  {
        fields?: { 
            /**
            * Represents the Tab Content field (a9026462-8ad8-48f9-a63d-45b1c3d05c00).
            */
            content?: Field<string>;

            /**
            * Represents the Tab Title field (6bcee0e2-15c0-43ad-84e2-350eae70db39).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem as an Item
    */
    export type TabItem_Item = Omit<Item, 'fields'> & TabItem

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem as a Component
    */
    export type TabItem_Component = ComponentProps & TabItem

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem
    */
    export type TabItemJson =  {
        
            /**
            * Represents the Tab Content field (a9026462-8ad8-48f9-a63d-45b1c3d05c00).
            */
            content?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Tab Title field (6bcee0e2-15c0-43ad-84e2-350eae70db39).
            */
            title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem Folder
    */
    export type TabItemFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem Folder as an Item
    */
    export type TabItemFolder_Item = Omit<Item, 'fields'> & TabItemFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem Folder as a Component
    */
    export type TabItemFolder_Component = ComponentProps & TabItemFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem Folder
    */
    export type TabItemFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem Parameters
    */
    export type TabItemParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem Parameters as an Item
    */
    export type TabItemParameters_Item = Omit<Item, 'fields'> & TabItemParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem Parameters as a Component
    */
    export type TabItemParameters_Component = ComponentProps & TabItemParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/Tab/TabItem Parameters
    */
    export type TabItemParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Lists.Tab.Constants {

    export const TabParameters = {
        TemplateId: "5b40c9cb-c1df-4049-afa8-fd10ddaddbed",
    
        BaseTemplateIds: [
        ]
    }
    export const TabItem = {
        TemplateId: "2bc18f52-ccf1-4d6b-8d59-8001beb81270",
    
        BaseTemplateIds: [
        ]
    }
    export const TabItemFolder = {
        TemplateId: "f10737e4-616e-4720-aff8-25fe40fbf94c",
    
        BaseTemplateIds: [
        ]
    }
    export const TabItemParameters = {
        TemplateId: "bc5235dd-725c-4dfd-8a5f-cab13539e58e",
    
        BaseTemplateIds: [
        ]
    }
}    


