
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Lists.VideoCardItem VideoCardItem Lists
// @ts-ignore
import { Lists as ListsVideoCardItemLists } from "./VideoCardItem.model"
// Template: Feature.HztlFoundation.Lists.CardList CardItem Lists
// @ts-ignore
import { Lists as ListsCardListLists } from "./CardList.model"
// Template: Feature.HztlFoundation.Lists.VideoCardItem VideoCardItem Folder Lists
// Template: Lists already imported
// Template: Feature.HztlFoundation.Lists.VideoCardItem VideoCardItem Parameters Lists
// Template: Lists already imported

export namespace Lists.VideoCardItem {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem
    */
    export type VideoCardItem = ListsCardListLists.CardList.CardItem &  {
        fields?: { 
            /**
            * Represents the Video Url field (e2718007-968a-4736-88ab-328c8a496d23).
            */
            videoUrl?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem as an Item
    */
    export type VideoCardItem_Item = Omit<Item, 'fields'> & VideoCardItem

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem as a Component
    */
    export type VideoCardItem_Component = ComponentProps & VideoCardItem

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem
    */
    export type VideoCardItemJson = ListsCardListLists.CardList.CardItemJson &  {
        
            /**
            * Represents the Video Url field (e2718007-968a-4736-88ab-328c8a496d23).
            */
            videoUrl?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem Folder
    */
    export type VideoCardItemFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem Folder as an Item
    */
    export type VideoCardItemFolder_Item = Omit<Item, 'fields'> & VideoCardItemFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem Folder as a Component
    */
    export type VideoCardItemFolder_Component = ComponentProps & VideoCardItemFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem Folder
    */
    export type VideoCardItemFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem Parameters
    */
    export type VideoCardItemParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem Parameters as an Item
    */
    export type VideoCardItemParameters_Item = Omit<Item, 'fields'> & VideoCardItemParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem Parameters as a Component
    */
    export type VideoCardItemParameters_Component = ComponentProps & VideoCardItemParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem Parameters
    */
    export type VideoCardItemParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Lists.VideoCardItem.Constants {

    export const VideoCardItem = {
        TemplateId: "4ee7e153-0d56-491f-9440-c77c4c6be9fa",
    
        BaseTemplateIds: [
            "3a7d27e5-b935-46da-b8fb-fe1e260957d8", 
        ]
    }
    export const VideoCardItemFolder = {
        TemplateId: "caf75ab7-0dac-4b71-8b89-d0b685cd0743",
    
        BaseTemplateIds: [
        ]
    }
    export const VideoCardItemParameters = {
        TemplateId: "c5d8dad0-0c78-4a16-a6f1-de30e51b9b55",
    
        BaseTemplateIds: [
        ]
    }
}    


