
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation Content Security Policy Settings Settings
// @ts-ignore
import { Settings as FeatureHztlFoundationSettings } from "./HztlFoundation.model"
// Template: Feature.HztlFoundation Global Folder GlobalData
// @ts-ignore
import { GlobalData as FeatureHztlFoundationGlobalData } from "./HztlFoundation.model"
// Template: Feature.HztlFoundation Share GlobalData
// Template: GlobalData already imported
// Template: Feature.HztlFoundation Share Folder GlobalData
// Template: GlobalData already imported
// Template: Feature.HztlFoundation Share Parameters GlobalData
// Template: GlobalData already imported
// Template: Feature.HztlFoundation Site Settings Settings
// Template: Settings already imported
// Template: Foundation.HztlFoundation _SocialSharingLinks Base
// @ts-ignore
import { Base as FoundationHztlFoundationBase } from "./HztlFoundation.model"

export namespace Settings {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Settings/Content Security Policy Settings
    */
    export type ContentSecurityPolicySettings =  {
        fields?: { 
            /**
            * Represents the connect-src field (126e6ebf-cb02-4971-8670-d1e5c2064681).
            */
            connectSource?: Field<string>;

            /**
            * Represents the fontSource field (edb6f6d8-56c8-4215-87fb-ba0db341153d).
            */
            fontSource?: Field<string>;

            /**
            * Represents the frame-src field (099fe72a-f649-465e-8214-b41f9cdff38e).
            */
            frameSource?: Field<string>;

            /**
            * Represents the img-src field (64e980cc-92bc-4df2-94b7-ac499e6d51e0).
            */
            imageSource?: Field<string>;

            /**
            * Represents the media-src field (21916b86-8697-4ec9-8424-7ea2e8806291).
            */
            mediaSource?: Field<string>;

            /**
            * Represents the script-src-elem field (8369d7b8-1a96-47b4-895c-a1003b7334a6).
            */
            scriptElement?: Field<string>;

            /**
            * Represents the script-src field (40328740-205d-49c0-9914-2140c66a1dd7).
            */
            scriptSource?: Field<string>;

            /**
            * Represents the style-src field (2b4a00d3-8fa4-4149-82b4-1cc461c17ddc).
            */
            styleSource?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Settings/Content Security Policy Settings as an Item
    */
    export type ContentSecurityPolicySettings_Item = Omit<Item, 'fields'> & ContentSecurityPolicySettings

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Settings/Content Security Policy Settings as a Component
    */
    export type ContentSecurityPolicySettings_Component = ComponentProps & ContentSecurityPolicySettings

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Settings/Content Security Policy Settings
    */
    export type ContentSecurityPolicySettingsJson =  {
        
            /**
            * Represents the connect-src field (126e6ebf-cb02-4971-8670-d1e5c2064681).
            */
            connectSource?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the fontSource field (edb6f6d8-56c8-4215-87fb-ba0db341153d).
            */
            fontSource?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the frame-src field (099fe72a-f649-465e-8214-b41f9cdff38e).
            */
            frameSource?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the img-src field (64e980cc-92bc-4df2-94b7-ac499e6d51e0).
            */
            imageSource?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the media-src field (21916b86-8697-4ec9-8424-7ea2e8806291).
            */
            mediaSource?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the script-src-elem field (8369d7b8-1a96-47b4-895c-a1003b7334a6).
            */
            scriptElement?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the script-src field (40328740-205d-49c0-9914-2140c66a1dd7).
            */
            scriptSource?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the style-src field (2b4a00d3-8fa4-4149-82b4-1cc461c17ddc).
            */
            styleSource?: {
                jsonValue: Field<string>
            };


    }
}
export namespace GlobalData {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Global Folder
    */
    export type GlobalFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Global Folder as an Item
    */
    export type GlobalFolder_Item = Omit<Item, 'fields'> & GlobalFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Global Folder as a Component
    */
    export type GlobalFolder_Component = ComponentProps & GlobalFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/GlobalData/Global Folder
    */
    export type GlobalFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Share
    */
    export type Share =  {
        fields?: { 
            /**
            * Represents the Icon field (9cd52dda-7372-4f7a-b894-4f34fc46daf1).
            */
            icon?: ImageField;

            /**
            * Represents the Title field (f4ff64a3-57f3-4ba6-a1c3-7ed756d7f93c).
            */
            title?: Field<string>;

            /**
            * Represents the Url field (b4226fe1-2b34-4f59-a4f3-b1ffbeff0778).
            */
            url?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Share as an Item
    */
    export type Share_Item = Omit<Item, 'fields'> & Share

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Share as a Component
    */
    export type Share_Component = ComponentProps & Share

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/GlobalData/Share
    */
    export type ShareJson =  {
        
            /**
            * Represents the Icon field (9cd52dda-7372-4f7a-b894-4f34fc46daf1).
            */
            icon?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Title field (f4ff64a3-57f3-4ba6-a1c3-7ed756d7f93c).
            */
            title?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Url field (b4226fe1-2b34-4f59-a4f3-b1ffbeff0778).
            */
            url?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Share Folder
    */
    export type ShareFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Share Folder as an Item
    */
    export type ShareFolder_Item = Omit<Item, 'fields'> & ShareFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Share Folder as a Component
    */
    export type ShareFolder_Component = ComponentProps & ShareFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/GlobalData/Share Folder
    */
    export type ShareFolderJson =  {
        

    }
}
export namespace GlobalData.RenderingParameters {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Rendering Parameters/Share Parameters
    */
    export type ShareParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Rendering Parameters/Share Parameters as an Item
    */
    export type ShareParameters_Item = Omit<Item, 'fields'> & ShareParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/GlobalData/Rendering Parameters/Share Parameters as a Component
    */
    export type ShareParameters_Component = ComponentProps & ShareParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/GlobalData/Rendering Parameters/Share Parameters
    */
    export type ShareParametersJson =  {
        

    }
}
export namespace Settings {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Settings/Site Settings
    */
    export type SiteSettings = FoundationHztlFoundationBase.SocialSharingLinks &  {
        fields?: { 
            /**
            * Represents the Brand Style field (fbea697f-f4bc-4617-8c8d-08169c6c4249).
            */
            brandStyle?: Field<string>;

            /**
            * Represents the Global Recommendation Widget Id field (94ca9407-7db4-4488-9067-933c4b5f157e).
            */
            globalRecommendationWidgetId?: Field<string>;

            /**
            * Represents the Global Search Preview Widget Id field (3e835ef2-7ca0-4b6b-aee8-a13427546b5a).
            */
            globalSearchPreviewWidgetId?: Field<string>;

            /**
            * Represents the Global Search Source Id field (317c910d-d5be-438a-b0bb-87e140d1ef44).
            */
            globalSearchSourceId?: Field<string>;

            /**
            * Represents the Global Search Widget Id field (c623c3c2-464a-420e-b86b-f338324f8f34).
            */
            globalSearchWidgetId?: Field<string>;

            /**
            * Represents the GTM ID field (20e8dc0b-b542-48c9-bfdc-cd27ac60f362).
            */
            gtmId?: Field<string>;

            /**
            * Represents the Number of Articles field (19529213-b3f6-41f0-9977-14b8cb0366ac).
            */
            noOfArticlesCount?: Field<number>;

            /**
            * Represents the Number of Related Articles field (d4c4a5fa-c639-40ed-8217-1fc79f646fd1).
            */
            noOfRelatedArticlesCount?: Field<number>;

            /**
            * Represents the Number of Search Results Count field (459b521b-94c2-4ed2-9a27-ffdc32d843b2).
            */
            noOfSearchResultsCount?: Field<number>;

            /**
            * Represents the Site Alerts field (6e0435a7-74f5-425c-a935-dd789081a3f2).
            */
            siteAlerts?: Item[];
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Settings/Site Settings as an Item
    */
    export type SiteSettings_Item = Omit<Item, 'fields'> & SiteSettings

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Settings/Site Settings as a Component
    */
    export type SiteSettings_Component = ComponentProps & SiteSettings

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Settings/Site Settings
    */
    export type SiteSettingsJson = FoundationHztlFoundationBase.SocialSharingLinksJson &  {
        
            /**
            * Represents the Brand Style field (fbea697f-f4bc-4617-8c8d-08169c6c4249).
            */
            brandStyle?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Global Recommendation Widget Id field (94ca9407-7db4-4488-9067-933c4b5f157e).
            */
            globalRecommendationWidgetId?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Global Search Preview Widget Id field (3e835ef2-7ca0-4b6b-aee8-a13427546b5a).
            */
            globalSearchPreviewWidgetId?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Global Search Source Id field (317c910d-d5be-438a-b0bb-87e140d1ef44).
            */
            globalSearchSourceId?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Global Search Widget Id field (c623c3c2-464a-420e-b86b-f338324f8f34).
            */
            globalSearchWidgetId?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the GTM ID field (20e8dc0b-b542-48c9-bfdc-cd27ac60f362).
            */
            gtmId?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Number of Articles field (19529213-b3f6-41f0-9977-14b8cb0366ac).
            */
            noOfArticlesCount?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Number of Related Articles field (d4c4a5fa-c639-40ed-8217-1fc79f646fd1).
            */
            noOfRelatedArticlesCount?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Number of Search Results Count field (459b521b-94c2-4ed2-9a27-ffdc32d843b2).
            */
            noOfSearchResultsCount?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Site Alerts field (6e0435a7-74f5-425c-a935-dd789081a3f2).
            */
            siteAlerts?: {
                jsonValue: Item[]
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Settings.Constants {

    export const ContentSecurityPolicySettings = {
        TemplateId: "f5b4868d-e8c0-46d9-a172-c069ea024f3a",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace GlobalData.Constants {

    export const GlobalFolder = {
        TemplateId: "1f14ced2-7051-4f4e-9f2c-6a06d28f72f9",
    
        BaseTemplateIds: [
        ]
    }
    export const Share = {
        TemplateId: "1b362c05-f549-4590-ab62-64eac1a2dbb5",
    
        BaseTemplateIds: [
        ]
    }
    export const ShareFolder = {
        TemplateId: "da0680d5-2227-42f0-a77c-0d658aac492f",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace GlobalData.RenderingParameters.Constants {

    export const ShareParameters = {
        TemplateId: "7f277372-52aa-4c0b-8bc1-0293126c3122",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Settings.Constants {

    export const SiteSettings = {
        TemplateId: "f6950030-ae2f-471f-ac34-d8f90a51ac33",
    
        BaseTemplateIds: [
            "61344593-348a-4e33-918c-8c3ad8ffb03f", 
        ]
    }
}    


