
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Foundation.HztlFoundation Enum Data
// @ts-ignore
import { Data as FoundationHztlFoundationData } from "./HztlFoundation.model"
// Template: Foundation.HztlFoundation Enum Folder Data
// Template: Data already imported
// Template: Foundation.HztlFoundation Generic Link Data
// Template: Data already imported
// Template: Foundation.HztlFoundation _SeoMetadataPlus Base
// @ts-ignore
import { Base as FoundationHztlFoundationBase } from "./HztlFoundation.model"
// Template: Foundation.HztlFoundation _SocialSharingLinks Base
// Template: Base already imported
// Template: Foundation.HztlFoundation _Theme Base
// Template: Base already imported

export namespace Data.Enums {

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Data/Enums/Enum
    */
    export type Enum =  {
        fields?: { 
            /**
            * Represents the Title field (fc36755b-1822-4d01-af06-3f294489b179).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Data/Enums/Enum as an Item
    */
    export type Enum_Item = Omit<Item, 'fields'> & Enum

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Data/Enums/Enum as a Component
    */
    export type Enum_Component = ComponentProps & Enum

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/HztlFoundation/Data/Enums/Enum
    */
    export type EnumJson =  {
        
            /**
            * Represents the Title field (fc36755b-1822-4d01-af06-3f294489b179).
            */
            title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Data/Enums/Enum Folder
    */
    export type EnumFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Data/Enums/Enum Folder as an Item
    */
    export type EnumFolder_Item = Omit<Item, 'fields'> & EnumFolder

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Data/Enums/Enum Folder as a Component
    */
    export type EnumFolder_Component = ComponentProps & EnumFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/HztlFoundation/Data/Enums/Enum Folder
    */
    export type EnumFolderJson =  {
        

    }
}
export namespace Data.Links {

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Data/Links/Generic Link
    */
    export type GenericLink =  {
        fields?: { 
            /**
            * Represents the Link field (1e5322d4-6c42-466f-ad23-32a4c7aeacc3).
            */
            link?: LinkField;
        }

    }

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Data/Links/Generic Link as an Item
    */
    export type GenericLink_Item = Omit<Item, 'fields'> & GenericLink

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Data/Links/Generic Link as a Component
    */
    export type GenericLink_Component = ComponentProps & GenericLink

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/HztlFoundation/Data/Links/Generic Link
    */
    export type GenericLinkJson =  {
        
            /**
            * Represents the Link field (1e5322d4-6c42-466f-ad23-32a4c7aeacc3).
            */
            link?: {
                jsonValue: LinkField
            };


    }
}
export namespace Base {

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Base/_SeoMetadataPlus
    */
    export type SeoMetadataPlus =  {
        fields?: { 
            /**
            * Represents the Canonical Url field (08e09a55-567c-4e56-aba8-96a95825b112).
            */
            canonicalUrl?: Field<string>;

            /**
            * Represents the Robots Meta Tag field (441b6887-d610-4cd5-a972-9098bdd41abf).
            */
            robotsMetaTag?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Base/_SeoMetadataPlus as an Item
    */
    export type SeoMetadataPlus_Item = Omit<Item, 'fields'> & SeoMetadataPlus

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Base/_SeoMetadataPlus as a Component
    */
    export type SeoMetadataPlus_Component = ComponentProps & SeoMetadataPlus

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/HztlFoundation/Base/_SeoMetadataPlus
    */
    export type SeoMetadataPlusJson =  {
        
            /**
            * Represents the Canonical Url field (08e09a55-567c-4e56-aba8-96a95825b112).
            */
            canonicalUrl?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Robots Meta Tag field (441b6887-d610-4cd5-a972-9098bdd41abf).
            */
            robotsMetaTag?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Base/_SocialSharingLinks
    */
    export type SocialSharingLinks =  {
        fields?: { 
            /**
            * Represents the Select Social Links field (5b4ab929-9363-4c7f-90f0-2a88322d0a33).
            */
            socialShareLinks?: Item[];
        }

    }

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Base/_SocialSharingLinks as an Item
    */
    export type SocialSharingLinks_Item = Omit<Item, 'fields'> & SocialSharingLinks

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Base/_SocialSharingLinks as a Component
    */
    export type SocialSharingLinks_Component = ComponentProps & SocialSharingLinks

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/HztlFoundation/Base/_SocialSharingLinks
    */
    export type SocialSharingLinksJson =  {
        
            /**
            * Represents the Select Social Links field (5b4ab929-9363-4c7f-90f0-2a88322d0a33).
            */
            socialShareLinks?: {
                jsonValue: Item[]
            };


    }

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Base/_Theme
    */
    export type Theme =  {
        fields?: { 
            /**
            * Represents the Theme field (1a2fef87-0e32-4847-9f73-4d9e785bc94e).
            */
            selectTheme?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Base/_Theme as an Item
    */
    export type Theme_Item = Omit<Item, 'fields'> & Theme

    /**
    * Represents the template /sitecore/templates/Foundation/HztlFoundation/Base/_Theme as a Component
    */
    export type Theme_Component = ComponentProps & Theme

    /**
    * Represents the GraphQL template /sitecore/templates/Foundation/HztlFoundation/Base/_Theme
    */
    export type ThemeJson =  {
        
            /**
            * Represents the Theme field (1a2fef87-0e32-4847-9f73-4d9e785bc94e).
            */
            selectTheme?: {
                jsonValue: Field<string>
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Data.Enums.Constants {

    export const Enum = {
        TemplateId: "626997bb-fc2a-4588-8e5b-17ac2a840706",
    
        BaseTemplateIds: [
        ]
    }
    export const EnumFolder = {
        TemplateId: "781d39ed-7ee4-480f-a2c6-2579510cfe4c",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Data.Links.Constants {

    export const GenericLink = {
        TemplateId: "b7e9466d-8242-4efc-a137-c21c9e181ecb",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace Base.Constants {

    export const SeoMetadataPlus = {
        TemplateId: "b8fbdf00-57dc-4bb7-85ec-c34cc401379e",
    
        BaseTemplateIds: [
        ]
    }
    export const SocialSharingLinks = {
        TemplateId: "61344593-348a-4e33-918c-8c3ad8ffb03f",
    
        BaseTemplateIds: [
        ]
    }
    export const Theme = {
        TemplateId: "2d5e2037-3132-4bcf-8654-79d99111292e",
    
        BaseTemplateIds: [
        ]
    }
}    


