
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Project.HztlFoundation Article Category Page PageTypes
// @ts-ignore
import { PageTypes as ProjectHztlFoundationPageTypes } from "./HztlFoundation.model"
// Template: Project.HztlFoundation GeneralPage Project
// @ts-ignore
import { Project as ProjectHztlFoundationProject } from "./HztlFoundation.model"
// Template: Foundation.HztlFoundation _SeoMetadataPlus Base
// @ts-ignore
import { Base as FoundationHztlFoundationBase } from "./HztlFoundation.model"
// Template: Feature.HztlFoundation.PageSpecific.ArticleListing _ArticleCategoryTags PageSpecific
// @ts-ignore
import { PageSpecific as PageSpecificArticleListingPageSpecific } from "./ArticleListing.model"
// Template: Feature.HztlFoundation.PageSpecific.ArticleListing _ArticleListingInformation PageSpecific
// Template: PageSpecific already imported
// Template: Project.HztlFoundation Article Detail Page PageTypes
// Template: PageTypes already imported
// Template: Project.HztlFoundation Article Landing Page PageTypes
// Template: PageTypes already imported
// Template: Project.HztlFoundation Editorial Page PageTypes
// Template: PageTypes already imported
// Template: Project.HztlFoundation Headless Site Project
// Template: Project already imported
// Template: Project.HztlFoundation Headless Tenant Project
// Template: Project already imported
// Template: Project.HztlFoundation JSS Settings Project
// Template: Project already imported
// Template: Project.HztlFoundation Page Design Folder Project
// Template: Project already imported
// Template: Project.HztlFoundation Page Designs Project
// Template: Project already imported
// Template: Project.HztlFoundation Partial Design Folder Project
// Template: Project already imported
// Template: Project.HztlFoundation Partial Designs Project
// Template: Project already imported
// Template: Project.HztlFoundation Search Results Page PageTypes
// Template: PageTypes already imported

export namespace PageTypes {

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Article Category Page
    */
    export type ArticleCategoryPage = ProjectHztlFoundationProject.HztlFoundation.GeneralPage & 
PageSpecificArticleListingPageSpecific.ArticleListing.ArticleCategoryTags & 
PageSpecificArticleListingPageSpecific.ArticleListing.ArticleListingInformation &  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Article Category Page as an Item
    */
    export type ArticleCategoryPage_Item = Omit<Item, 'fields'> & ArticleCategoryPage

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Article Category Page as a Component
    */
    export type ArticleCategoryPage_Component = ComponentProps & ArticleCategoryPage

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Page Types/Article Category Page
    */
    export type ArticleCategoryPageJson = ProjectHztlFoundationProject.HztlFoundation.GeneralPageJson & 
PageSpecificArticleListingPageSpecific.ArticleListing.ArticleCategoryTagsJson & 
PageSpecificArticleListingPageSpecific.ArticleListing.ArticleListingInformationJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Article Detail Page
    */
    export type ArticleDetailPage = ProjectHztlFoundationProject.HztlFoundation.GeneralPage &  {
        fields?: { 
            /**
            * Represents the Author Name field (1f8ea6ef-332a-4d41-952f-887c473e057e).
            */
            authorName?: Field<string>;

            /**
            * Represents the Description field (0e9394bc-0af5-412c-95c9-d4434b9516f4).
            */
            description?: Field<string>;

            /**
            * Represents the Heading field (6e6ea041-0b1a-40d6-aa84-17fb03d1266b).
            */
            heading?: Field<string>;

            /**
            * Represents the Image field (b278f67b-22ec-4e23-9094-004c1845b470).
            */
            image?: ImageField;

            /**
            * Represents the Published Date field (b88ed689-8669-4163-b082-157bc8fe15ce).
            */
            publishedDate?: Field<string>;

            /**
            * Represents the Sub Heading field (192d7f05-fffb-4b2f-9c5f-4a6964b31175).
            */
            subHeading?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Article Detail Page as an Item
    */
    export type ArticleDetailPage_Item = Omit<Item, 'fields'> & ArticleDetailPage

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Article Detail Page as a Component
    */
    export type ArticleDetailPage_Component = ComponentProps & ArticleDetailPage

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Page Types/Article Detail Page
    */
    export type ArticleDetailPageJson = ProjectHztlFoundationProject.HztlFoundation.GeneralPageJson &  {
        
            /**
            * Represents the Author Name field (1f8ea6ef-332a-4d41-952f-887c473e057e).
            */
            authorName?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Description field (0e9394bc-0af5-412c-95c9-d4434b9516f4).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Heading field (6e6ea041-0b1a-40d6-aa84-17fb03d1266b).
            */
            heading?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Image field (b278f67b-22ec-4e23-9094-004c1845b470).
            */
            image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Published Date field (b88ed689-8669-4163-b082-157bc8fe15ce).
            */
            publishedDate?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Sub Heading field (192d7f05-fffb-4b2f-9c5f-4a6964b31175).
            */
            subHeading?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Article Landing Page
    */
    export type ArticleLandingPage = ProjectHztlFoundationProject.HztlFoundation.GeneralPage & 
PageSpecificArticleListingPageSpecific.ArticleListing.ArticleCategoryTags & 
PageSpecificArticleListingPageSpecific.ArticleListing.ArticleListingInformation &  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Article Landing Page as an Item
    */
    export type ArticleLandingPage_Item = Omit<Item, 'fields'> & ArticleLandingPage

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Article Landing Page as a Component
    */
    export type ArticleLandingPage_Component = ComponentProps & ArticleLandingPage

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Page Types/Article Landing Page
    */
    export type ArticleLandingPageJson = ProjectHztlFoundationProject.HztlFoundation.GeneralPageJson & 
PageSpecificArticleListingPageSpecific.ArticleListing.ArticleCategoryTagsJson & 
PageSpecificArticleListingPageSpecific.ArticleListing.ArticleListingInformationJson &  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Editorial Page
    */
    export type EditorialPage = ProjectHztlFoundationProject.HztlFoundation.GeneralPage &  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Editorial Page as an Item
    */
    export type EditorialPage_Item = Omit<Item, 'fields'> & EditorialPage

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Editorial Page as a Component
    */
    export type EditorialPage_Component = ComponentProps & EditorialPage

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Page Types/Editorial Page
    */
    export type EditorialPageJson = ProjectHztlFoundationProject.HztlFoundation.GeneralPageJson &  {
        

    }
}
export namespace Project.HztlFoundation {

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/GeneralPage
    */
    export type GeneralPage = FoundationHztlFoundationBase.SeoMetadataPlus &  {
        fields?: { 
            /**
            * Represents the Hero Description field (55c06709-e693-465f-baa5-1031d286ee7d).
            */
            heroDescription?: Field<string>;

            /**
            * Represents the Hero Image field (7dae2916-357a-4155-8a58-990e3fcffe78).
            */
            heroImage?: ImageField;

            /**
            * Represents the Hero Title field (0dada022-54b0-4bcb-ae7c-da83234d1c03).
            */
            heroTitle?: Field<string>;

            /**
            * Represents the Page Description field (2ec2526b-52e4-469d-83a7-401d7b50ae1b).
            */
            pageDescription?: Field<string>;

            /**
            * Represents the Page Title field (9c063550-df49-46a3-99c6-f830a981a018).
            */
            pageTitle?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/GeneralPage as an Item
    */
    export type GeneralPage_Item = Omit<Item, 'fields'> & GeneralPage

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/GeneralPage as a Component
    */
    export type GeneralPage_Component = ComponentProps & GeneralPage

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/GeneralPage
    */
    export type GeneralPageJson = FoundationHztlFoundationBase.SeoMetadataPlusJson &  {
        
            /**
            * Represents the Hero Description field (55c06709-e693-465f-baa5-1031d286ee7d).
            */
            heroDescription?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Hero Image field (7dae2916-357a-4155-8a58-990e3fcffe78).
            */
            heroImage?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Hero Title field (0dada022-54b0-4bcb-ae7c-da83234d1c03).
            */
            heroTitle?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Page Description field (2ec2526b-52e4-469d-83a7-401d7b50ae1b).
            */
            pageDescription?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Page Title field (9c063550-df49-46a3-99c6-f830a981a018).
            */
            pageTitle?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Headless Site
    */
    export type HeadlessSite =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Headless Site as an Item
    */
    export type HeadlessSite_Item = Omit<Item, 'fields'> & HeadlessSite

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Headless Site as a Component
    */
    export type HeadlessSite_Component = ComponentProps & HeadlessSite

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Headless Site
    */
    export type HeadlessSiteJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Headless Tenant
    */
    export type HeadlessTenant =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Headless Tenant as an Item
    */
    export type HeadlessTenant_Item = Omit<Item, 'fields'> & HeadlessTenant

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Headless Tenant as a Component
    */
    export type HeadlessTenant_Component = ComponentProps & HeadlessTenant

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Headless Tenant
    */
    export type HeadlessTenantJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/JSS Settings
    */
    export type JssSettings =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/JSS Settings as an Item
    */
    export type JssSettings_Item = Omit<Item, 'fields'> & JssSettings

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/JSS Settings as a Component
    */
    export type JssSettings_Component = ComponentProps & JssSettings

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/JSS Settings
    */
    export type JssSettingsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Design Folder
    */
    export type PageDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Design Folder as an Item
    */
    export type PageDesignFolder_Item = Omit<Item, 'fields'> & PageDesignFolder

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Design Folder as a Component
    */
    export type PageDesignFolder_Component = ComponentProps & PageDesignFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Page Design Folder
    */
    export type PageDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Designs
    */
    export type PageDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Designs as an Item
    */
    export type PageDesigns_Item = Omit<Item, 'fields'> & PageDesigns

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Designs as a Component
    */
    export type PageDesigns_Component = ComponentProps & PageDesigns

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Page Designs
    */
    export type PageDesignsJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Partial Design Folder
    */
    export type PartialDesignFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Partial Design Folder as an Item
    */
    export type PartialDesignFolder_Item = Omit<Item, 'fields'> & PartialDesignFolder

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Partial Design Folder as a Component
    */
    export type PartialDesignFolder_Component = ComponentProps & PartialDesignFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Partial Design Folder
    */
    export type PartialDesignFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Partial Designs
    */
    export type PartialDesigns =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Partial Designs as an Item
    */
    export type PartialDesigns_Item = Omit<Item, 'fields'> & PartialDesigns

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Partial Designs as a Component
    */
    export type PartialDesigns_Component = ComponentProps & PartialDesigns

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Partial Designs
    */
    export type PartialDesignsJson =  {
        

    }
}
export namespace PageTypes {

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Search Results Page
    */
    export type SearchResultsPage = ProjectHztlFoundationProject.HztlFoundation.GeneralPage &  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Search Results Page as an Item
    */
    export type SearchResultsPage_Item = Omit<Item, 'fields'> & SearchResultsPage

    /**
    * Represents the template /sitecore/templates/Project/HztlFoundation/Page Types/Search Results Page as a Component
    */
    export type SearchResultsPage_Component = ComponentProps & SearchResultsPage

    /**
    * Represents the GraphQL template /sitecore/templates/Project/HztlFoundation/Page Types/Search Results Page
    */
    export type SearchResultsPageJson = ProjectHztlFoundationProject.HztlFoundation.GeneralPageJson &  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace PageTypes.Constants {

    export const ArticleCategoryPage = {
        TemplateId: "61f24e8b-82ce-46d6-8c3f-6fe0f3ac6c0a",
    
        BaseTemplateIds: [
            "b936184f-fca2-4acc-b7ed-b9f4e6170b8c", 
            "b8fbdf00-57dc-4bb7-85ec-c34cc401379e", 
            "028e9710-148f-465a-83e5-cfabcb32d8bc", 
            "c248b5c9-990f-452f-b2ba-e9f1fb093a6e", 
        ]
    }
    export const ArticleDetailPage = {
        TemplateId: "375dcaaa-f94c-42ce-b2ab-3fb1d8871fd9",
    
        BaseTemplateIds: [
            "b936184f-fca2-4acc-b7ed-b9f4e6170b8c", 
            "b8fbdf00-57dc-4bb7-85ec-c34cc401379e", 
        ]
    }
    export const ArticleLandingPage = {
        TemplateId: "26a34b77-76f6-43c1-9de7-077111d96da8",
    
        BaseTemplateIds: [
            "b936184f-fca2-4acc-b7ed-b9f4e6170b8c", 
            "b8fbdf00-57dc-4bb7-85ec-c34cc401379e", 
            "028e9710-148f-465a-83e5-cfabcb32d8bc", 
            "c248b5c9-990f-452f-b2ba-e9f1fb093a6e", 
        ]
    }
    export const EditorialPage = {
        TemplateId: "92a53ac9-0bf7-40aa-aa38-a2a77d72afda",
    
        BaseTemplateIds: [
            "b936184f-fca2-4acc-b7ed-b9f4e6170b8c", 
            "b8fbdf00-57dc-4bb7-85ec-c34cc401379e", 
        ]
    }
}
export namespace Project.HztlFoundation.Constants {

    export const GeneralPage = {
        TemplateId: "b936184f-fca2-4acc-b7ed-b9f4e6170b8c",
    
        BaseTemplateIds: [
            "b8fbdf00-57dc-4bb7-85ec-c34cc401379e", 
        ]
    }
    export const HeadlessSite = {
        TemplateId: "ac5c5911-839e-4130-8675-5d77b750cb58",
    
        BaseTemplateIds: [
        ]
    }
    export const HeadlessTenant = {
        TemplateId: "c3ad7833-764b-4de0-b42f-dafcdc6a93ef",
    
        BaseTemplateIds: [
        ]
    }
    export const JssSettings = {
        TemplateId: "6d778a82-f230-42f7-9ebb-0c25ebc4a6cc",
    
        BaseTemplateIds: [
        ]
    }
    export const PageDesignFolder = {
        TemplateId: "9c75cc3a-b79b-47e2-a801-40c6f7414c6f",
    
        BaseTemplateIds: [
        ]
    }
    export const PageDesigns = {
        TemplateId: "11d22431-f378-4a68-8ee5-ffc1ea5005cf",
    
        BaseTemplateIds: [
        ]
    }
    export const PartialDesignFolder = {
        TemplateId: "e2f40205-f385-4134-a57f-bab1f3850e2f",
    
        BaseTemplateIds: [
        ]
    }
    export const PartialDesigns = {
        TemplateId: "f004e782-2325-407d-aa8f-f3195808f8ac",
    
        BaseTemplateIds: [
        ]
    }
}
export namespace PageTypes.Constants {

    export const SearchResultsPage = {
        TemplateId: "74b82706-2a95-4356-ace3-a48ba4da0e4f",
    
        BaseTemplateIds: [
            "b936184f-fca2-4acc-b7ed-b9f4e6170b8c", 
            "b8fbdf00-57dc-4bb7-85ec-c34cc401379e", 
        ]
    }
}    


