---
ID: "e0b5413e-7833-463a-9aad-eb1adede8182"
Parent: "028e9710-148f-465a-83e5-cfabcb32d8bc"
Template: "028e9710-148f-465a-83e5-cfabcb32d8bc"
Path: /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/_ArticleCategoryTags/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250617T174401Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sreekrishnanks@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sreekrishnanks@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bcf287ef-8b99-4acb-98e7-2313f060030b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sreekrishnanks@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250617T174401Z
