---
ID: "a53d9039-8fc9-457c-a77d-7879463415e3"
Parent: "b52221d6-10ed-44e6-9a71-3eec9ef7eb15"
Template: "b52221d6-10ed-44e6-9a71-3eec9ef7eb15"
Path: /sitecore/templates/Feature/HztlFoundation/Media/InlineIFrame/Rendering Parameters/InlineIFrame/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "676c011f-3f2d-40c8-9090-371a7c03e2ee"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250331T083620Z
