---
ID: "3db4ba47-55b3-4cac-a63d-3fa35c1a42d5"
Parent: "6a2ac055-af15-49f1-a7e5-01fa0edde5be"
Template: "f6950030-ae2f-471f-ac34-d8f90a51ac33"
Path: /sitecore/content/HztlFoundation/HelloWorld Corp/Settings/Site Settings
SharedFields:
- ID: "20e8dc0b-b542-48c9-bfdc-cd27ac60f362"
  Hint: gtmId
  Value: "G-NDRSX4SWMG"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "027dba2f-5506-4096-8859-76c8a2bdf81c"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250320T132954Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7bd533bb-6344-47d1-9387-c312a78d0f3a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\erosen@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250422T153502Z
