---
ID: "b87327c2-bb31-4da2-a69f-a5a087dff2e5"
Parent: "14858c0f-f195-4361-b8d0-75b85d5640b6"
Template: "14858c0f-f195-4361-b8d0-75b85d5640b6"
Path: /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1cf12c51-3c25-4909-b7fe-ffccc040d6c3"
      Hint: alertType
      Value: "{320706DA-5A21-419E-B292-73158137E446}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250429T145844Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\anandakumar.a@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\anandakumar.a@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "571c1569-7271-4ee3-af03-7e1ed6f4baf4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\anandakumar.a@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250429T145851Z
