
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.PageSpecific.ArticleListing Article Listing PageSpecific
// @ts-ignore
import { PageSpecific as PageSpecificArticleListingPageSpecific } from "./ArticleListing.model"
// Template: Feature.HztlFoundation.PageSpecific.ArticleListing Article Listing Folder PageSpecific
// Template: PageSpecific already imported
// Template: Feature.HztlFoundation.PageSpecific.ArticleListing Article Listing Parameters PageSpecific
// Template: PageSpecific already imported
// Template: Feature.HztlFoundation.PageSpecific.ArticleListing _ArticleCategoryTags PageSpecific
// Template: PageSpecific already imported
// Template: Feature.HztlFoundation.PageSpecific.ArticleListing _ArticleListingInformation PageSpecific
// Template: PageSpecific already imported

export namespace PageSpecific.ArticleListing {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing
    */
    export type ArticleListing =  {
        fields?: { 
            /**
            * Represents the Search Description field (c5d4a281-2780-4804-8b1e-35b027ec6f4f).
            */
            description?: Field<string>;

            /**
            * Represents the No Search Result field (b66bc227-17d5-4023-8a3f-38a475d4a32b).
            */
            noResultFoundMessage?: Field<string>;

            /**
            * Represents the Results Per Page field (76dfa02b-027b-425e-9bbc-e9141b0e2b2a).
            */
            numberOfArticles?: Field<number>;

            /**
            * Represents the Text field (4066fc0f-b6c2-43d6-94f8-6911e49c7199).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing as an Item
    */
    export type ArticleListing_Item = Omit<Item, 'fields'> & ArticleListing

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing as a Component
    */
    export type ArticleListing_Component = ComponentProps & ArticleListing

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing
    */
    export type ArticleListingJson =  {
        
            /**
            * Represents the Search Description field (c5d4a281-2780-4804-8b1e-35b027ec6f4f).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the No Search Result field (b66bc227-17d5-4023-8a3f-38a475d4a32b).
            */
            noResultFoundMessage?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Results Per Page field (76dfa02b-027b-425e-9bbc-e9141b0e2b2a).
            */
            numberOfArticles?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Text field (4066fc0f-b6c2-43d6-94f8-6911e49c7199).
            */
            title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing Folder
    */
    export type ArticleListingFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing Folder as an Item
    */
    export type ArticleListingFolder_Item = Omit<Item, 'fields'> & ArticleListingFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing Folder as a Component
    */
    export type ArticleListingFolder_Component = ComponentProps & ArticleListingFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing Folder
    */
    export type ArticleListingFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing Parameters
    */
    export type ArticleListingParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing Parameters as an Item
    */
    export type ArticleListingParameters_Item = Omit<Item, 'fields'> & ArticleListingParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing Parameters as a Component
    */
    export type ArticleListingParameters_Component = ComponentProps & ArticleListingParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/Article Listing Parameters
    */
    export type ArticleListingParametersJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/_ArticleCategoryTags
    */
    export type ArticleCategoryTags =  {
        fields?: { 
            /**
            * Represents the Category Name field (83526e85-6947-4aef-b9d4-9ce95d95e885).
            */
            categoryName?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/_ArticleCategoryTags as an Item
    */
    export type ArticleCategoryTags_Item = Omit<Item, 'fields'> & ArticleCategoryTags

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/_ArticleCategoryTags as a Component
    */
    export type ArticleCategoryTags_Component = ComponentProps & ArticleCategoryTags

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/_ArticleCategoryTags
    */
    export type ArticleCategoryTagsJson =  {
        
            /**
            * Represents the Category Name field (83526e85-6947-4aef-b9d4-9ce95d95e885).
            */
            categoryName?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/_ArticleListingInformation
    */
    export type ArticleListingInformation =  {
        fields?: { 
            /**
            * Represents the Article List Title field (c4a18b98-907e-42ed-ba42-b441b00d005c).
            */
            articleListTitle?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/_ArticleListingInformation as an Item
    */
    export type ArticleListingInformation_Item = Omit<Item, 'fields'> & ArticleListingInformation

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/_ArticleListingInformation as a Component
    */
    export type ArticleListingInformation_Component = ComponentProps & ArticleListingInformation

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/ArticleListing/_ArticleListingInformation
    */
    export type ArticleListingInformationJson =  {
        
            /**
            * Represents the Article List Title field (c4a18b98-907e-42ed-ba42-b441b00d005c).
            */
            articleListTitle?: {
                jsonValue: Field<string>
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace PageSpecific.ArticleListing.Constants {

    export const ArticleListing = {
        TemplateId: "a630e62c-1690-4c61-865d-94409c7d8bf4",
    
        BaseTemplateIds: [
        ]
    }
    export const ArticleListingFolder = {
        TemplateId: "ed81febb-f450-4636-873d-db384b0c6fde",
    
        BaseTemplateIds: [
        ]
    }
    export const ArticleListingParameters = {
        TemplateId: "67e422e2-88de-43b5-8d7c-98e8c6b82bb1",
    
        BaseTemplateIds: [
        ]
    }
    export const ArticleCategoryTags = {
        TemplateId: "028e9710-148f-465a-83e5-cfabcb32d8bc",
    
        BaseTemplateIds: [
        ]
    }
    export const ArticleListingInformation = {
        TemplateId: "c248b5c9-990f-452f-b2ba-e9f1fb093a6e",
    
        BaseTemplateIds: [
        ]
    }
}    


