
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.PageSpecific.PopularArticles Popular Articles PageSpecific
// @ts-ignore
import { PageSpecific as PageSpecificPopularArticlesPageSpecific } from "./PopularArticles.model"
// Template: Feature.HztlFoundation.PageSpecific.PopularArticles Popular Articles Folder PageSpecific
// Template: PageSpecific already imported
// Template: Feature.HztlFoundation.PageSpecific.PopularArticles Popular Articles Parameters PageSpecific
// Template: PageSpecific already imported

export namespace PageSpecific.PopularArticles {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles
    */
    export type PopularArticles =  {
        fields?: { 
            /**
            * Represents the Description field (670fa922-ffdc-4c16-a751-57c4d27af533).
            */
            description?: Field<string>;

            /**
            * Represents the No Articles Found Message field (1b83aaf8-e801-4d0c-9ce4-f527624c5e09).
            */
            noResultFoundMessage?: Field<string>;

            /**
            * Represents the Number of Articles field (05e6b749-c5fd-4e1c-89f5-62ad79fc6fb4).
            */
            numberOfArticles?: Field<number>;

            /**
            * Represents the Text field (b938a2c6-d641-4807-a98a-0e22fc5fcf18).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles as an Item
    */
    export type PopularArticles_Item = Omit<Item, 'fields'> & PopularArticles

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles as a Component
    */
    export type PopularArticles_Component = ComponentProps & PopularArticles

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles
    */
    export type PopularArticlesJson =  {
        
            /**
            * Represents the Description field (670fa922-ffdc-4c16-a751-57c4d27af533).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the No Articles Found Message field (1b83aaf8-e801-4d0c-9ce4-f527624c5e09).
            */
            noResultFoundMessage?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Number of Articles field (05e6b749-c5fd-4e1c-89f5-62ad79fc6fb4).
            */
            numberOfArticles?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Text field (b938a2c6-d641-4807-a98a-0e22fc5fcf18).
            */
            title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles Folder
    */
    export type PopularArticlesFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles Folder as an Item
    */
    export type PopularArticlesFolder_Item = Omit<Item, 'fields'> & PopularArticlesFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles Folder as a Component
    */
    export type PopularArticlesFolder_Component = ComponentProps & PopularArticlesFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles Folder
    */
    export type PopularArticlesFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles Parameters
    */
    export type PopularArticlesParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles Parameters as an Item
    */
    export type PopularArticlesParameters_Item = Omit<Item, 'fields'> & PopularArticlesParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles Parameters as a Component
    */
    export type PopularArticlesParameters_Component = ComponentProps & PopularArticlesParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/PopularArticles/Popular Articles Parameters
    */
    export type PopularArticlesParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace PageSpecific.PopularArticles.Constants {

    export const PopularArticles = {
        TemplateId: "b249e48b-fce7-404b-8864-3790ee6f21d1",
    
        BaseTemplateIds: [
        ]
    }
    export const PopularArticlesFolder = {
        TemplateId: "27e1f398-523e-4644-9754-50dad56099f3",
    
        BaseTemplateIds: [
        ]
    }
    export const PopularArticlesParameters = {
        TemplateId: "708e51c8-9586-4bb3-9e3b-b9eaa91a0d8d",
    
        BaseTemplateIds: [
        ]
    }
}    


