
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.PageSpecific.RelatedArticles Related Articles PageSpecific
// @ts-ignore
import { PageSpecific as PageSpecificRelatedArticlesPageSpecific } from "./RelatedArticles.model"
// Template: Feature.HztlFoundation.PageSpecific.RelatedArticles Related Articles Folder PageSpecific
// Template: PageSpecific already imported
// Template: Feature.HztlFoundation.PageSpecific.RelatedArticles Related Articles Parameters PageSpecific
// Template: PageSpecific already imported

export namespace PageSpecific.RelatedArticles {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles
    */
    export type RelatedArticles =  {
        fields?: { 
            /**
            * Represents the Description field (31fb692a-baeb-4098-bf55-400710438fb8).
            */
            description?: Field<string>;

            /**
            * Represents the No Articles Found Message field (e7ec4ff8-b13c-42aa-b405-bce799e52e91).
            */
            noResultFoundMessage?: Field<string>;

            /**
            * Represents the Number of Articles field (00d1158f-ff30-4c30-b9e8-16dccfc7b885).
            */
            numberOfArticles?: Field<number>;

            /**
            * Represents the Text field (8109a582-0884-4f34-ba0f-2ef78c4345f0).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles as an Item
    */
    export type RelatedArticles_Item = Omit<Item, 'fields'> & RelatedArticles

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles as a Component
    */
    export type RelatedArticles_Component = ComponentProps & RelatedArticles

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles
    */
    export type RelatedArticlesJson =  {
        
            /**
            * Represents the Description field (31fb692a-baeb-4098-bf55-400710438fb8).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the No Articles Found Message field (e7ec4ff8-b13c-42aa-b405-bce799e52e91).
            */
            noResultFoundMessage?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Number of Articles field (00d1158f-ff30-4c30-b9e8-16dccfc7b885).
            */
            numberOfArticles?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Text field (8109a582-0884-4f34-ba0f-2ef78c4345f0).
            */
            title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles Folder
    */
    export type RelatedArticlesFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles Folder as an Item
    */
    export type RelatedArticlesFolder_Item = Omit<Item, 'fields'> & RelatedArticlesFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles Folder as a Component
    */
    export type RelatedArticlesFolder_Component = ComponentProps & RelatedArticlesFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles Folder
    */
    export type RelatedArticlesFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles Parameters
    */
    export type RelatedArticlesParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles Parameters as an Item
    */
    export type RelatedArticlesParameters_Item = Omit<Item, 'fields'> & RelatedArticlesParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles Parameters as a Component
    */
    export type RelatedArticlesParameters_Component = ComponentProps & RelatedArticlesParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/RelatedArticles/Related Articles Parameters
    */
    export type RelatedArticlesParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace PageSpecific.RelatedArticles.Constants {

    export const RelatedArticles = {
        TemplateId: "e0a8c0ae-71cb-4125-9d50-bf8bb2994363",
    
        BaseTemplateIds: [
        ]
    }
    export const RelatedArticlesFolder = {
        TemplateId: "2178b8e5-448e-44a7-9b6e-424999dc8721",
    
        BaseTemplateIds: [
        ]
    }
    export const RelatedArticlesParameters = {
        TemplateId: "e25a7dbd-1241-42fb-8457-fe5b85547a3a",
    
        BaseTemplateIds: [
        ]
    }
}    


