
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.PageSpecific.SearchResult Search Result PageSpecific
// @ts-ignore
import { PageSpecific as PageSpecificSearchResultPageSpecific } from "./SearchResult.model"
// Template: Feature.HztlFoundation.PageSpecific.SearchResult Search Result Folder PageSpecific
// Template: PageSpecific already imported
// Template: Feature.HztlFoundation.PageSpecific.SearchResult Search Result Parameters PageSpecific
// Template: PageSpecific already imported

export namespace PageSpecific.SearchResult {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result
    */
    export type SearchResult =  {
        fields?: { 
            /**
            * Represents the Filter Title field (e551012d-37b0-4e6a-ac35-044e10bd24bb).
            */
            filterTitle?: Field<string>;

            /**
            * Represents the No Search Result field (e77e0eec-a796-4b6d-aae9-0ee9c31a2bc8).
            */
            noSearchResult?: Field<string>;

            /**
            * Represents the Results Per Page field (589c0450-7b13-4d83-9b20-56b8ecb0cce0).
            */
            resultsPerPage?: Field<number>;

            /**
            * Represents the Search Description field (172ecb98-2874-457b-9319-45f94c79110a).
            */
            searchDescription?: Field<string>;

            /**
            * Represents the Text field (177eb211-26fd-428f-be5a-f6246d5326ac).
            */
            searchTitle?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result as an Item
    */
    export type SearchResult_Item = Omit<Item, 'fields'> & SearchResult

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result as a Component
    */
    export type SearchResult_Component = ComponentProps & SearchResult

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result
    */
    export type SearchResultJson =  {
        
            /**
            * Represents the Filter Title field (e551012d-37b0-4e6a-ac35-044e10bd24bb).
            */
            filterTitle?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the No Search Result field (e77e0eec-a796-4b6d-aae9-0ee9c31a2bc8).
            */
            noSearchResult?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Results Per Page field (589c0450-7b13-4d83-9b20-56b8ecb0cce0).
            */
            resultsPerPage?: {
                jsonValue: Field<number>
            };

            /**
            * Represents the Search Description field (172ecb98-2874-457b-9319-45f94c79110a).
            */
            searchDescription?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text field (177eb211-26fd-428f-be5a-f6246d5326ac).
            */
            searchTitle?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result Folder
    */
    export type SearchResultFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result Folder as an Item
    */
    export type SearchResultFolder_Item = Omit<Item, 'fields'> & SearchResultFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result Folder as a Component
    */
    export type SearchResultFolder_Component = ComponentProps & SearchResultFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result Folder
    */
    export type SearchResultFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result Parameters
    */
    export type SearchResultParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result Parameters as an Item
    */
    export type SearchResultParameters_Item = Omit<Item, 'fields'> & SearchResultParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result Parameters as a Component
    */
    export type SearchResultParameters_Component = ComponentProps & SearchResultParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/PageSpecific/SearchResult/Search Result Parameters
    */
    export type SearchResultParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace PageSpecific.SearchResult.Constants {

    export const SearchResult = {
        TemplateId: "97cbfab1-b046-4bb7-a00c-5e7e0724eacb",
    
        BaseTemplateIds: [
        ]
    }
    export const SearchResultFolder = {
        TemplateId: "3f8a4e79-8821-41d4-b146-02525fb33481",
    
        BaseTemplateIds: [
        ]
    }
    export const SearchResultParameters = {
        TemplateId: "320f7f52-8d85-41f3-a0db-9209d36966b0",
    
        BaseTemplateIds: [
        ]
    }
}    


