---
ID: "21e6fa9a-9358-494a-80f2-dca078dd9b7c"
Parent: "cb2117cd-3c6c-4dc7-8055-45ee49299cbb"
Template: "f6950030-ae2f-471f-ac34-d8f90a51ac33"
Path: /sitecore/content/HztlFoundation/Nimbus Goods/Settings/Site Settings
SharedFields:
- ID: "20e8dc0b-b542-48c9-bfdc-cd27ac60f362"
  Hint: gtmId
  Value: "G-ERYXJC5G0J"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "534c0710-88fc-4674-8046-ef5859212692"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250321T142801Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dly@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dly@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4cb84988-2fc9-4794-a3db-5b1117e9a6a2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\erosen@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250422T153407Z
