---
ID: "c6f35703-6995-47e1-9edc-196318d43b9f"
Parent: "e1eb445d-2d66-45ac-aa79-ab0f9d9a6e6d"
Template: "e1eb445d-2d66-45ac-aa79-ab0f9d9a6e6d"
Path: /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Full Bleed Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "97cc723c-7902-43ce-b167-d127395a1354"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\anandakumar.a@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250708T202140Z
