---
ID: "89646c5b-0ac8-4993-ac18-0b66cbec3d0b"
Parent: "c964d341-2d71-4159-b469-e69d8094b38c"
Template: "c964d341-2d71-4159-b469-e69d8094b38c"
Path: /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "23e3e225-8796-43c2-a4c2-03e1083e9bca"
      Hint: image
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240515T114752Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mchaniyara@horizontal.com
    - ID: "52bf742a-97a4-450b-ad56-0a5cbe3152d3"
      Hint: description
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mchaniyara@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "071c3124-2dc8-4ec2-b5db-af8212cd49e8"
    - ID: "9184d55e-ad12-46e4-9bc3-4167eb75e6e2"
      Hint: heading
      Value: 
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\anandakumar.a@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250722T195903Z
