---
ID: "d3954360-31a0-47a3-8e18-1d296db6d38a"
Parent: "e96ccca9-b415-424a-9381-65017814e2aa"
Template: "e96ccca9-b415-424a-9381-65017814e2aa"
Path: /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5e8ceb15-3001-43da-bbed-27d4283081aa"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\anandakumar.a@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250722T200313Z
