
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Content.Alert Alert Content
// @ts-ignore
import { Content as ContentAlertContent } from "./Alert.model"
// Template: Feature.HztlFoundation.Content.Alert Alert Folder Content
// Template: Content already imported
// Template: Feature.HztlFoundation.Content.Alert Alert Parameters Content
// Template: Content already imported

export namespace Content.Alert {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert
    */
    export type Alert =  {
        fields?: { 
            /**
            * Represents the Alert CTA field (2cb8973d-4bc4-4cc0-8a85-294a7d00494f).
            */
            alertCTA?: LinkField;

            /**
            * Represents the Alert Text field (d1a9a38f-88b0-49df-8161-81e0fccfd6e3).
            */
            alertText?: Field<string>;

            /**
            * Represents the Alert Type field (1cf12c51-3c25-4909-b7fe-ffccc040d6c3).
            */
            alertType?: Item;

            /**
            * Represents the End Date field (4388a003-bdfd-4e00-ad07-8ae81af8efbf).
            */
            endDate?: Field<string>;

            /**
            * Represents the Start Date field (20c95e1e-7ea5-4c47-a7c1-7b5429dad0de).
            */
            startDate?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert as an Item
    */
    export type Alert_Item = Omit<Item, 'fields'> & Alert

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert as a Component
    */
    export type Alert_Component = ComponentProps & Alert

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert
    */
    export type AlertJson =  {
        
            /**
            * Represents the Alert CTA field (2cb8973d-4bc4-4cc0-8a85-294a7d00494f).
            */
            alertCTA?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Alert Text field (d1a9a38f-88b0-49df-8161-81e0fccfd6e3).
            */
            alertText?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Alert Type field (1cf12c51-3c25-4909-b7fe-ffccc040d6c3).
            */
            alertType?: {
                jsonValue: Item
            };

            /**
            * Represents the End Date field (4388a003-bdfd-4e00-ad07-8ae81af8efbf).
            */
            endDate?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Start Date field (20c95e1e-7ea5-4c47-a7c1-7b5429dad0de).
            */
            startDate?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert Folder
    */
    export type AlertFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert Folder as an Item
    */
    export type AlertFolder_Item = Omit<Item, 'fields'> & AlertFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert Folder as a Component
    */
    export type AlertFolder_Component = ComponentProps & AlertFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert Folder
    */
    export type AlertFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert Parameters
    */
    export type AlertParameters =  {
        fields?: { 
            /**
            * Represents the Alert Type field (edcaa4bc-ada0-4c71-ab46-4d7182ba215b).
            */
            "Alert Type"?: Item;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert Parameters as an Item
    */
    export type AlertParameters_Item = Omit<Item, 'fields'> & AlertParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert Parameters as a Component
    */
    export type AlertParameters_Component = ComponentProps & AlertParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Alert/Alert Parameters
    */
    export type AlertParametersJson =  {
        
            /**
            * Represents the Alert Type field (edcaa4bc-ada0-4c71-ab46-4d7182ba215b).
            */
            "Alert Type"?: {
                jsonValue: Item
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Content.Alert.Constants {

    export const Alert = {
        TemplateId: "14858c0f-f195-4361-b8d0-75b85d5640b6",
    
        BaseTemplateIds: [
        ]
    }
    export const AlertFolder = {
        TemplateId: "bfa7aefc-b066-4c4e-98b5-db06f39cbd51",
    
        BaseTemplateIds: [
        ]
    }
    export const AlertParameters = {
        TemplateId: "e13bf109-b5d3-4e8d-aad3-0002251b29be",
    
        BaseTemplateIds: [
        ]
    }
}    


