
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Content.CodeEmbed Code Embed Content
// @ts-ignore
import { Content as ContentCodeEmbedContent } from "./CodeEmbed.model"
// Template: Feature.HztlFoundation.Content.CodeEmbed Code Embed Folder Content
// Template: Content already imported
// Template: Feature.HztlFoundation.Content.CodeEmbed Code Embed Parameters Content
// Template: Content already imported

export namespace Content.CodeEmbed {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed
    */
    export type CodeEmbed =  {
        fields?: { 
            /**
            * Represents the Additional Tag Attributes field (e965c1ba-af56-4dfb-8f31-49b68a49b5a4).
            */
            additionalTagAttributes?: Field<string>;

            /**
            * Represents the Enabled field (a25bf32a-6364-4bcd-8188-b5ca8ef094cd).
            */
            enabled?: Field<boolean>;

            /**
            * Represents the HTML Code field (77737f16-be69-4480-b8c0-83f0706a1e87).
            */
            htmlCode?: Field<string>;

            /**
            * Represents the Script - Do not include the surrounding "<script>" tags field (510f0ba9-926b-4799-a745-178ee5f4b86c).
            */
            script?: Field<string>;

            /**
            * Represents the Script ID field (c63068e3-2ede-471e-b71f-19c1bdfbddf1).
            */
            scriptId?: Field<string>;

            /**
            * Represents the Script Source URL field (406ce508-669f-446e-80be-2d229bd660a3).
            */
            scriptSourceUrl?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed as an Item
    */
    export type CodeEmbed_Item = Omit<Item, 'fields'> & CodeEmbed

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed as a Component
    */
    export type CodeEmbed_Component = ComponentProps & CodeEmbed

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed
    */
    export type CodeEmbedJson =  {
        
            /**
            * Represents the Additional Tag Attributes field (e965c1ba-af56-4dfb-8f31-49b68a49b5a4).
            */
            additionalTagAttributes?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Enabled field (a25bf32a-6364-4bcd-8188-b5ca8ef094cd).
            */
            enabled?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the HTML Code field (77737f16-be69-4480-b8c0-83f0706a1e87).
            */
            htmlCode?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Script - Do not include the surrounding "<script>" tags field (510f0ba9-926b-4799-a745-178ee5f4b86c).
            */
            script?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Script ID field (c63068e3-2ede-471e-b71f-19c1bdfbddf1).
            */
            scriptId?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Script Source URL field (406ce508-669f-446e-80be-2d229bd660a3).
            */
            scriptSourceUrl?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed Folder
    */
    export type CodeEmbedFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed Folder as an Item
    */
    export type CodeEmbedFolder_Item = Omit<Item, 'fields'> & CodeEmbedFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed Folder as a Component
    */
    export type CodeEmbedFolder_Component = ComponentProps & CodeEmbedFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed Folder
    */
    export type CodeEmbedFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed Parameters
    */
    export type CodeEmbedParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed Parameters as an Item
    */
    export type CodeEmbedParameters_Item = Omit<Item, 'fields'> & CodeEmbedParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed Parameters as a Component
    */
    export type CodeEmbedParameters_Component = ComponentProps & CodeEmbedParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/CodeEmbed/Code Embed Parameters
    */
    export type CodeEmbedParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Content.CodeEmbed.Constants {

    export const CodeEmbed = {
        TemplateId: "03976078-693f-4a5a-9fa7-b52395ae6514",
    
        BaseTemplateIds: [
        ]
    }
    export const CodeEmbedFolder = {
        TemplateId: "c2fd20b9-183e-4854-968b-4ab64f82d314",
    
        BaseTemplateIds: [
        ]
    }
    export const CodeEmbedParameters = {
        TemplateId: "185327e4-c257-4d35-a583-d4d033384683",
    
        BaseTemplateIds: [
        ]
    }
}    


