
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Content.Feature Feature Content
// @ts-ignore
import { Content as ContentFeatureContent } from "./Feature.model"
// Template: Feature.HztlFoundation.Content.Feature Feature Folder Content
// Template: Content already imported
// Template: Feature.HztlFoundation.Content.Feature Feature Parameters Content
// Template: Content already imported
// Template: Foundation.HztlFoundation _Theme Base
// @ts-ignore
import { Base as FoundationHztlFoundationBase } from "./HztlFoundation.model"

export namespace Content.Feature {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature
    */
    export type Feature =  {
        fields?: { 
            /**
            * Represents the Background Image field (43f7fbcb-f445-453e-b92f-1563ccbe4155).
            */
            background?: ImageField;

            /**
            * Represents the CTA 1 Link field (9905ceea-d426-45ff-af94-b319d21c8a7d).
            */
            cta1Link?: LinkField;

            /**
            * Represents the CTA 2 Link field (963fc139-0eb6-4bd7-973b-8d3200e8085a).
            */
            cta2Link?: LinkField;

            /**
            * Represents the Text 3 field (3d509257-2210-4ca8-8eab-4ff81be38cd7).
            */
            description?: Field<string>;

            /**
            * Represents the Eyebrow Text field (0192df1e-0509-4f1f-95ac-345ca6a4b136).
            */
            eyebrow?: Field<string>;

            /**
            * Represents the Text field (2931056b-8441-4648-8827-3d4b324a77b1).
            */
            headline?: Field<string>;

            /**
            * Represents the Icon field (50967d4e-f5e0-4a64-93b4-2f7f5db4c95b).
            */
            icon?: ImageField;

            /**
            * Represents the Sub-Headline field (ecb67a30-93d1-447d-a472-5bb7379452f7).
            */
            subHeadline?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature as an Item
    */
    export type Feature_Item = Omit<Item, 'fields'> & Feature

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature as a Component
    */
    export type Feature_Component = ComponentProps & Feature

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature
    */
    export type FeatureJson =  {
        
            /**
            * Represents the Background Image field (43f7fbcb-f445-453e-b92f-1563ccbe4155).
            */
            background?: {
                jsonValue: ImageField
            };

            /**
            * Represents the CTA 1 Link field (9905ceea-d426-45ff-af94-b319d21c8a7d).
            */
            cta1Link?: {
                jsonValue: LinkField
            };

            /**
            * Represents the CTA 2 Link field (963fc139-0eb6-4bd7-973b-8d3200e8085a).
            */
            cta2Link?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Text 3 field (3d509257-2210-4ca8-8eab-4ff81be38cd7).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Eyebrow Text field (0192df1e-0509-4f1f-95ac-345ca6a4b136).
            */
            eyebrow?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text field (2931056b-8441-4648-8827-3d4b324a77b1).
            */
            headline?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Icon field (50967d4e-f5e0-4a64-93b4-2f7f5db4c95b).
            */
            icon?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Sub-Headline field (ecb67a30-93d1-447d-a472-5bb7379452f7).
            */
            subHeadline?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature Folder
    */
    export type FeatureFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature Folder as an Item
    */
    export type FeatureFolder_Item = Omit<Item, 'fields'> & FeatureFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature Folder as a Component
    */
    export type FeatureFolder_Component = ComponentProps & FeatureFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature Folder
    */
    export type FeatureFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature Parameters
    */
    export type FeatureParameters = FoundationHztlFoundationBase.Theme &  {
        fields?: { 
            /**
            * Represents the Text Alignment field (fb9dbae4-7eca-4e69-9f44-ba78440b66d6).
            */
            alignment?: Field<string>;

            /**
            * Represents the Background Layout field (e764b826-02a6-47a0-9162-2d01e7c2b78b).
            */
            layout?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature Parameters as an Item
    */
    export type FeatureParameters_Item = Omit<Item, 'fields'> & FeatureParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature Parameters as a Component
    */
    export type FeatureParameters_Component = ComponentProps & FeatureParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Feature/Feature Parameters
    */
    export type FeatureParametersJson = FoundationHztlFoundationBase.ThemeJson &  {
        
            /**
            * Represents the Text Alignment field (fb9dbae4-7eca-4e69-9f44-ba78440b66d6).
            */
            alignment?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Background Layout field (e764b826-02a6-47a0-9162-2d01e7c2b78b).
            */
            layout?: {
                jsonValue: Field<string>
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Content.Feature.Constants {

    export const Feature = {
        TemplateId: "72864051-ce2a-4fed-9df1-ff688035cd67",
    
        BaseTemplateIds: [
        ]
    }
    export const FeatureFolder = {
        TemplateId: "64f5674f-b399-41e4-953d-646a384184f4",
    
        BaseTemplateIds: [
        ]
    }
    export const FeatureParameters = {
        TemplateId: "56ca0f9e-111a-4895-b220-75b47383d44f",
    
        BaseTemplateIds: [
            "2d5e2037-3132-4bcf-8654-79d99111292e", 
        ]
    }
}    


