
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Content.FeatureSideBySide Feature Side by Side Content
// @ts-ignore
import { Content as ContentFeatureSideBySideContent } from "./FeatureSideBySide.model"
// Template: Feature.HztlFoundation.Content.FeatureSideBySide Feature Side by Side Folder Content
// Template: Content already imported
// Template: Feature.HztlFoundation.Content.FeatureSideBySide Feature Side by Side Parameters Content
// Template: Content already imported
// Template: Foundation.HztlFoundation _Theme Base
// @ts-ignore
import { Base as FoundationHztlFoundationBase } from "./HztlFoundation.model"

export namespace Content.FeatureSideBySide {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side
    */
    export type FeatureSideBySide =  {
        fields?: { 
            /**
            * Represents the CTA 1 Link field (e42d6793-6e1b-4037-90f9-0128d6f698f4).
            */
            cta1Link?: LinkField;

            /**
            * Represents the CTA 2 Link field (9261a06c-7423-40a1-ab74-90b84f44ade2).
            */
            cta2Link?: LinkField;

            /**
            * Represents the Text 3 field (52bf742a-97a4-450b-ad56-0a5cbe3152d3).
            */
            description?: Field<string>;

            /**
            * Represents the Eyebrow field (7c5e3c34-c0da-4afe-9293-aa3432895850).
            */
            eyebrow?: Field<string>;

            /**
            * Represents the Text field (9184d55e-ad12-46e4-9bc3-4167eb75e6e2).
            */
            heading?: Field<string>;

            /**
            * Represents the __Standard Werte field (23e3e225-8796-43c2-a4c2-03e1083e9bca).
            */
            image?: ImageField;

            /**
            * Represents the Sub Heading field (ca26fc2d-d134-4baf-a5b3-5e0d2c574e23).
            */
            subHeading?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side as an Item
    */
    export type FeatureSideBySide_Item = Omit<Item, 'fields'> & FeatureSideBySide

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side as a Component
    */
    export type FeatureSideBySide_Component = ComponentProps & FeatureSideBySide

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side
    */
    export type FeatureSideBySideJson =  {
        
            /**
            * Represents the CTA 1 Link field (e42d6793-6e1b-4037-90f9-0128d6f698f4).
            */
            cta1Link?: {
                jsonValue: LinkField
            };

            /**
            * Represents the CTA 2 Link field (9261a06c-7423-40a1-ab74-90b84f44ade2).
            */
            cta2Link?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Text 3 field (52bf742a-97a4-450b-ad56-0a5cbe3152d3).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Eyebrow field (7c5e3c34-c0da-4afe-9293-aa3432895850).
            */
            eyebrow?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text field (9184d55e-ad12-46e4-9bc3-4167eb75e6e2).
            */
            heading?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the __Standard Werte field (23e3e225-8796-43c2-a4c2-03e1083e9bca).
            */
            image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Sub Heading field (ca26fc2d-d134-4baf-a5b3-5e0d2c574e23).
            */
            subHeading?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side Folder
    */
    export type FeatureSideBySideFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side Folder as an Item
    */
    export type FeatureSideBySideFolder_Item = Omit<Item, 'fields'> & FeatureSideBySideFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side Folder as a Component
    */
    export type FeatureSideBySideFolder_Component = ComponentProps & FeatureSideBySideFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side Folder
    */
    export type FeatureSideBySideFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side Parameters
    */
    export type FeatureSideBySideParameters = FoundationHztlFoundationBase.Theme &  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side Parameters as an Item
    */
    export type FeatureSideBySideParameters_Item = Omit<Item, 'fields'> & FeatureSideBySideParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side Parameters as a Component
    */
    export type FeatureSideBySideParameters_Component = ComponentProps & FeatureSideBySideParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/FeatureSideBySide/Feature Side by Side Parameters
    */
    export type FeatureSideBySideParametersJson = FoundationHztlFoundationBase.ThemeJson &  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Content.FeatureSideBySide.Constants {

    export const FeatureSideBySide = {
        TemplateId: "c964d341-2d71-4159-b469-e69d8094b38c",
    
        BaseTemplateIds: [
        ]
    }
    export const FeatureSideBySideFolder = {
        TemplateId: "fc6a1b65-6a38-419b-8bab-1cdfe18169e2",
    
        BaseTemplateIds: [
        ]
    }
    export const FeatureSideBySideParameters = {
        TemplateId: "e96ccca9-b415-424a-9381-65017814e2aa",
    
        BaseTemplateIds: [
            "2d5e2037-3132-4bcf-8654-79d99111292e", 
        ]
    }
}    


