
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Content.Hero Hero Content
// @ts-ignore
import { Content as ContentHeroContent } from "./Hero.model"
// Template: Feature.HztlFoundation.Content.Hero Hero Folder Content
// Template: Content already imported
// Template: Feature.HztlFoundation.Content.Hero Hero Parameters Content
// Template: Content already imported
// Template: Foundation.HztlFoundation _Theme Base
// @ts-ignore
import { Base as FoundationHztlFoundationBase } from "./HztlFoundation.model"

export namespace Content.Hero {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero
    */
    export type Hero =  {
        fields?: { 
            /**
            * Represents the CTA 1 Link field (a0fd42c3-9121-45bb-bf22-0222bb7b8200).
            */
            cta1Link?: LinkField;

            /**
            * Represents the CTA 2 Link field (567a9f0d-2cf2-4162-91b2-b33cf5ff9595).
            */
            cta2Link?: LinkField;

            /**
            * Represents the Text 3 field (72c8e421-0bdd-46ff-a012-3835f6e52060).
            */
            description?: Field<string>;

            /**
            * Represents the Eyebrow field (b2a899a0-0ad0-45f4-a9a7-4a87e101c8d0).
            */
            eyebrow?: Field<string>;

            /**
            * Represents the Text field (05be0e84-140d-4d03-9b12-8c4a9dc2a25b).
            */
            heading?: Field<string>;

            /**
            * Represents the __Standard Werte field (828b4c29-c92b-420f-8173-be73559bb31b).
            */
            image?: ImageField;

            /**
            * Represents the Sub Heading field (75178fe9-063e-494c-a1d2-157f99ad633c).
            */
            subHeading?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero as an Item
    */
    export type Hero_Item = Omit<Item, 'fields'> & Hero

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero as a Component
    */
    export type Hero_Component = ComponentProps & Hero

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero
    */
    export type HeroJson =  {
        
            /**
            * Represents the CTA 1 Link field (a0fd42c3-9121-45bb-bf22-0222bb7b8200).
            */
            cta1Link?: {
                jsonValue: LinkField
            };

            /**
            * Represents the CTA 2 Link field (567a9f0d-2cf2-4162-91b2-b33cf5ff9595).
            */
            cta2Link?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Text 3 field (72c8e421-0bdd-46ff-a012-3835f6e52060).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Eyebrow field (b2a899a0-0ad0-45f4-a9a7-4a87e101c8d0).
            */
            eyebrow?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text field (05be0e84-140d-4d03-9b12-8c4a9dc2a25b).
            */
            heading?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the __Standard Werte field (828b4c29-c92b-420f-8173-be73559bb31b).
            */
            image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Sub Heading field (75178fe9-063e-494c-a1d2-157f99ad633c).
            */
            subHeading?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero Folder
    */
    export type HeroFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero Folder as an Item
    */
    export type HeroFolder_Item = Omit<Item, 'fields'> & HeroFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero Folder as a Component
    */
    export type HeroFolder_Component = ComponentProps & HeroFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero Folder
    */
    export type HeroFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero Parameters
    */
    export type HeroParameters = FoundationHztlFoundationBase.Theme &  {
        fields?: { 
            /**
            * Represents the Background Layout field (a0beaf54-6056-4857-a4ba-9381c5358db6).
            */
            layout?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero Parameters as an Item
    */
    export type HeroParameters_Item = Omit<Item, 'fields'> & HeroParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero Parameters as a Component
    */
    export type HeroParameters_Component = ComponentProps & HeroParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Hero/Hero Parameters
    */
    export type HeroParametersJson = FoundationHztlFoundationBase.ThemeJson &  {
        
            /**
            * Represents the Background Layout field (a0beaf54-6056-4857-a4ba-9381c5358db6).
            */
            layout?: {
                jsonValue: Field<string>
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Content.Hero.Constants {

    export const Hero = {
        TemplateId: "4bda55f9-dbec-4f86-85fe-e42132b4dee6",
    
        BaseTemplateIds: [
        ]
    }
    export const HeroFolder = {
        TemplateId: "fcd9b72d-9922-426f-a0de-9546d030279d",
    
        BaseTemplateIds: [
        ]
    }
    export const HeroParameters = {
        TemplateId: "e49ce774-5c1d-4727-9796-a256da64893a",
    
        BaseTemplateIds: [
            "2d5e2037-3132-4bcf-8654-79d99111292e", 
        ]
    }
}    


