
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Content.Modal Modal Content
// @ts-ignore
import { Content as ContentModalContent } from "./Modal.model"
// Template: Feature.HztlFoundation.Content.Modal Modal Folder Content
// Template: Content already imported
// Template: Feature.HztlFoundation.Content.Modal Modal Parameters Content
// Template: Content already imported

export namespace Content.Modal {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal
    */
    export type Modal =  {
        fields?: { 
            /**
            * Represents the Modal Aria Label field (abf7dbc9-bb80-4d33-b15d-04188dc6e027).
            */
            label?: Field<string>;

            /**
            * Represents the Modal Id field (737891b0-d2c7-4dbc-a090-b140aaf8948a).
            */
            modalId?: Field<string>;

            /**
            * Represents the Open OnLoad field (27706ce8-a10b-489b-ad0c-4bd2e685faaa).
            */
            openOnLoad?: Field<boolean>;

            /**
            * Represents the Modal Size field (00a5b2be-d942-469d-b348-1dea6839fbe1).
            */
            size?: Field<string>;

            /**
            * Represents the Modal Title field (392a9b53-e3e9-4cf7-8863-c7a57caafa2d).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal as an Item
    */
    export type Modal_Item = Omit<Item, 'fields'> & Modal

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal as a Component
    */
    export type Modal_Component = ComponentProps & Modal

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal
    */
    export type ModalJson =  {
        
            /**
            * Represents the Modal Aria Label field (abf7dbc9-bb80-4d33-b15d-04188dc6e027).
            */
            label?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Modal Id field (737891b0-d2c7-4dbc-a090-b140aaf8948a).
            */
            modalId?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Open OnLoad field (27706ce8-a10b-489b-ad0c-4bd2e685faaa).
            */
            openOnLoad?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Modal Size field (00a5b2be-d942-469d-b348-1dea6839fbe1).
            */
            size?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Modal Title field (392a9b53-e3e9-4cf7-8863-c7a57caafa2d).
            */
            title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal Folder
    */
    export type ModalFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal Folder as an Item
    */
    export type ModalFolder_Item = Omit<Item, 'fields'> & ModalFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal Folder as a Component
    */
    export type ModalFolder_Component = ComponentProps & ModalFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal Folder
    */
    export type ModalFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal Parameters
    */
    export type ModalParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal Parameters as an Item
    */
    export type ModalParameters_Item = Omit<Item, 'fields'> & ModalParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal Parameters as a Component
    */
    export type ModalParameters_Component = ComponentProps & ModalParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Modal/Modal Parameters
    */
    export type ModalParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Content.Modal.Constants {

    export const Modal = {
        TemplateId: "38df8869-da3e-4248-855c-5b2d232e8e53",
    
        BaseTemplateIds: [
        ]
    }
    export const ModalFolder = {
        TemplateId: "d7585a9a-c415-4901-a91e-568606eda847",
    
        BaseTemplateIds: [
        ]
    }
    export const ModalParameters = {
        TemplateId: "587d5d1e-7779-4593-bae3-12b8e751b984",
    
        BaseTemplateIds: [
        ]
    }
}    


