
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Content.PageTitle Page Title Parameters Content
// @ts-ignore
import { Content as ContentPageTitleContent } from "./PageTitle.model"
// Template: Foundation.HztlFoundation _Theme Base
// @ts-ignore
import { Base as FoundationHztlFoundationBase } from "./HztlFoundation.model"
// Template: Feature.HztlFoundation.Content.PageTitle PageTitle Content
// Template: Content already imported
// Template: Feature.HztlFoundation.Content.PageTitle PageTitle Folder Content
// Template: Content already imported

export namespace Content.PageTitle {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/Page Title Parameters
    */
    export type PageTitleParameters = FoundationHztlFoundationBase.Theme &  {
        fields?: { 
            /**
            * Represents the Text Alignment field (ad0467c3-b799-4cbb-9258-ecc43fa3ff04).
            */
            alignment?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/Page Title Parameters as an Item
    */
    export type PageTitleParameters_Item = Omit<Item, 'fields'> & PageTitleParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/Page Title Parameters as a Component
    */
    export type PageTitleParameters_Component = ComponentProps & PageTitleParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/Page Title Parameters
    */
    export type PageTitleParametersJson = FoundationHztlFoundationBase.ThemeJson &  {
        
            /**
            * Represents the Text Alignment field (ad0467c3-b799-4cbb-9258-ecc43fa3ff04).
            */
            alignment?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/PageTitle
    */
    export type PageTitle =  {
        fields?: { 
            /**
            * Represents the CTA Link field (0bb5db30-e76c-4df2-901a-657fbed2b9fb).
            */
            ctaLink?: LinkField;

            /**
            * Represents the Text 3 field (e2cd8cf2-8e7d-439f-ad1e-7e50488b5d1d).
            */
            description?: Field<string>;

            /**
            * Represents the Text field (4f02c15d-eacb-46e6-ac3e-e143d205e411).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/PageTitle as an Item
    */
    export type PageTitle_Item = Omit<Item, 'fields'> & PageTitle

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/PageTitle as a Component
    */
    export type PageTitle_Component = ComponentProps & PageTitle

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/PageTitle
    */
    export type PageTitleJson =  {
        
            /**
            * Represents the CTA Link field (0bb5db30-e76c-4df2-901a-657fbed2b9fb).
            */
            ctaLink?: {
                jsonValue: LinkField
            };

            /**
            * Represents the Text 3 field (e2cd8cf2-8e7d-439f-ad1e-7e50488b5d1d).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text field (4f02c15d-eacb-46e6-ac3e-e143d205e411).
            */
            title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/PageTitle Folder
    */
    export type PageTitleFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/PageTitle Folder as an Item
    */
    export type PageTitleFolder_Item = Omit<Item, 'fields'> & PageTitleFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/PageTitle Folder as a Component
    */
    export type PageTitleFolder_Component = ComponentProps & PageTitleFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/PageTitle/PageTitle Folder
    */
    export type PageTitleFolderJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Content.PageTitle.Constants {

    export const PageTitleParameters = {
        TemplateId: "c8272344-bdc2-455e-8457-f19245a9ac26",
    
        BaseTemplateIds: [
            "2d5e2037-3132-4bcf-8654-79d99111292e", 
        ]
    }
    export const PageTitle = {
        TemplateId: "c416e668-c12b-4a03-a411-c4ab54454cc4",
    
        BaseTemplateIds: [
        ]
    }
    export const PageTitleFolder = {
        TemplateId: "c04c75a8-2b85-4f80-8951-0a0afa11a1e5",
    
        BaseTemplateIds: [
        ]
    }
}    


