
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Content.Quote Quote Content
// @ts-ignore
import { Content as ContentQuoteContent } from "./Quote.model"
// Template: Feature.HztlFoundation.Content.Quote Quote Folder Content
// Template: Content already imported
// Template: Feature.HztlFoundation.Content.Quote Quote Parameters Content
// Template: Content already imported
// Template: Foundation.HztlFoundation _Theme Base
// @ts-ignore
import { Base as FoundationHztlFoundationBase } from "./HztlFoundation.model"

export namespace Content.Quote {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote
    */
    export type Quote =  {
        fields?: { 
            /**
            * Represents the Text 3 field (cc25a7bb-2b6a-4c9e-977f-129ec9ab7bce).
            */
            description?: Field<string>;

            /**
            * Represents the Image field (5a15b904-0c00-4936-ba56-a25a2af4e7aa).
            */
            image?: ImageField;

            /**
            * Represents the Quotee Name field (e84db727-1d54-4fc3-b5be-dd8648946d5e).
            */
            name?: Field<string>;

            /**
            * Represents the Text field (5109afa8-b9ec-4458-b6ef-2191376d131d).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote as an Item
    */
    export type Quote_Item = Omit<Item, 'fields'> & Quote

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote as a Component
    */
    export type Quote_Component = ComponentProps & Quote

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote
    */
    export type QuoteJson =  {
        
            /**
            * Represents the Text 3 field (cc25a7bb-2b6a-4c9e-977f-129ec9ab7bce).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Image field (5a15b904-0c00-4936-ba56-a25a2af4e7aa).
            */
            image?: {
                jsonValue: ImageField
            };

            /**
            * Represents the Quotee Name field (e84db727-1d54-4fc3-b5be-dd8648946d5e).
            */
            name?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Text field (5109afa8-b9ec-4458-b6ef-2191376d131d).
            */
            title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote Folder
    */
    export type QuoteFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote Folder as an Item
    */
    export type QuoteFolder_Item = Omit<Item, 'fields'> & QuoteFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote Folder as a Component
    */
    export type QuoteFolder_Component = ComponentProps & QuoteFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote Folder
    */
    export type QuoteFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote Parameters
    */
    export type QuoteParameters = FoundationHztlFoundationBase.Theme &  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote Parameters as an Item
    */
    export type QuoteParameters_Item = Omit<Item, 'fields'> & QuoteParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote Parameters as a Component
    */
    export type QuoteParameters_Component = ComponentProps & QuoteParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/Quote/Quote Parameters
    */
    export type QuoteParametersJson = FoundationHztlFoundationBase.ThemeJson &  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Content.Quote.Constants {

    export const Quote = {
        TemplateId: "47471e5b-65bb-43bb-a137-8dbacafa40d8",
    
        BaseTemplateIds: [
        ]
    }
    export const QuoteFolder = {
        TemplateId: "f986b0c2-d807-4951-8448-e40b344d64a5",
    
        BaseTemplateIds: [
        ]
    }
    export const QuoteParameters = {
        TemplateId: "963191bb-cd2c-4dc3-951d-99e37d416ad0",
    
        BaseTemplateIds: [
            "2d5e2037-3132-4bcf-8654-79d99111292e", 
        ]
    }
}    


