
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Content.RTE RTE Content
// @ts-ignore
import { Content as ContentRTEContent } from "./RTE.model"
// Template: Feature.HztlFoundation.Content.RTE RTE Folder Content
// Template: Content already imported
// Template: Feature.HztlFoundation.Content.RTE RTE Parameters Content
// Template: Content already imported

export namespace Content.Rte {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE
    */
    export type Rte =  {
        fields?: { 
            /**
            * Represents the Text field (a536de85-0e9e-4041-9736-aa7cc093984d).
            */
            text?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE as an Item
    */
    export type Rte_Item = Omit<Item, 'fields'> & Rte

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE as a Component
    */
    export type Rte_Component = ComponentProps & Rte

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE
    */
    export type RteJson =  {
        
            /**
            * Represents the Text field (a536de85-0e9e-4041-9736-aa7cc093984d).
            */
            text?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE Folder
    */
    export type RteFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE Folder as an Item
    */
    export type RteFolder_Item = Omit<Item, 'fields'> & RteFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE Folder as a Component
    */
    export type RteFolder_Component = ComponentProps & RteFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE Folder
    */
    export type RteFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE Parameters
    */
    export type RteParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE Parameters as an Item
    */
    export type RteParameters_Item = Omit<Item, 'fields'> & RteParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE Parameters as a Component
    */
    export type RteParameters_Component = ComponentProps & RteParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Content/RTE/RTE Parameters
    */
    export type RteParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Content.Rte.Constants {

    export const Rte = {
        TemplateId: "0effe34a-636f-4288-ba3b-0af056aad42b",
    
        BaseTemplateIds: [
        ]
    }
    export const RteFolder = {
        TemplateId: "4a82d02b-9a50-409a-8c0a-b9213eee735d",
    
        BaseTemplateIds: [
        ]
    }
    export const RteParameters = {
        TemplateId: "0ce03778-0d61-4fb0-a95e-61e7236201ed",
    
        BaseTemplateIds: [
        ]
    }
}    


