
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Layout.Container Container 25-75 Parameters Layout
// @ts-ignore
import { Layout as LayoutContainerLayout } from "./Container.model"
// Template: Feature.HztlFoundation.Layout.Container Container 50-50 Parameters Layout
// Template: Layout already imported
// Template: Feature.HztlFoundation.Layout.Container Container 75-25 Parameters Layout
// Template: Layout already imported
// Template: Feature.HztlFoundation.Layout.Container Container Center 75 Parameters Layout
// Template: Layout already imported
// Template: Feature.HztlFoundation.Layout.Container Container Full Bleed Parameters Layout
// Template: Layout already imported
// Template: Feature.HztlFoundation.Layout.Container Container Full Width Parameters Layout
// Template: Layout already imported

export namespace Layout.Container {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 25-75 Parameters
    */
    export type Container2575Parameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 25-75 Parameters as an Item
    */
    export type Container2575Parameters_Item = Omit<Item, 'fields'> & Container2575Parameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 25-75 Parameters as a Component
    */
    export type Container2575Parameters_Component = ComponentProps & Container2575Parameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 25-75 Parameters
    */
    export type Container2575ParametersJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 50-50 Parameters
    */
    export type Container5050Parameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 50-50 Parameters as an Item
    */
    export type Container5050Parameters_Item = Omit<Item, 'fields'> & Container5050Parameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 50-50 Parameters as a Component
    */
    export type Container5050Parameters_Component = ComponentProps & Container5050Parameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 50-50 Parameters
    */
    export type Container5050ParametersJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 75-25 Parameters
    */
    export type Container7525Parameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 75-25 Parameters as an Item
    */
    export type Container7525Parameters_Item = Omit<Item, 'fields'> & Container7525Parameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 75-25 Parameters as a Component
    */
    export type Container7525Parameters_Component = ComponentProps & Container7525Parameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container 75-25 Parameters
    */
    export type Container7525ParametersJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Center 75 Parameters
    */
    export type ContainerCenter75Parameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Center 75 Parameters as an Item
    */
    export type ContainerCenter75Parameters_Item = Omit<Item, 'fields'> & ContainerCenter75Parameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Center 75 Parameters as a Component
    */
    export type ContainerCenter75Parameters_Component = ComponentProps & ContainerCenter75Parameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Center 75 Parameters
    */
    export type ContainerCenter75ParametersJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Full Bleed Parameters
    */
    export type ContainerFullBleedParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Full Bleed Parameters as an Item
    */
    export type ContainerFullBleedParameters_Item = Omit<Item, 'fields'> & ContainerFullBleedParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Full Bleed Parameters as a Component
    */
    export type ContainerFullBleedParameters_Component = ComponentProps & ContainerFullBleedParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Full Bleed Parameters
    */
    export type ContainerFullBleedParametersJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Full Width Parameters
    */
    export type ContainerFullWidthParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Full Width Parameters as an Item
    */
    export type ContainerFullWidthParameters_Item = Omit<Item, 'fields'> & ContainerFullWidthParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Full Width Parameters as a Component
    */
    export type ContainerFullWidthParameters_Component = ComponentProps & ContainerFullWidthParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Full Width Parameters
    */
    export type ContainerFullWidthParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Layout.Container.Constants {

    export const Container2575Parameters = {
        TemplateId: "a8483b72-bd84-4215-ae2a-b7498c77338e",
    
        BaseTemplateIds: [
        ]
    }
    export const Container5050Parameters = {
        TemplateId: "30811cbe-a14c-4ce2-9d33-7baca6c4838e",
    
        BaseTemplateIds: [
        ]
    }
    export const Container7525Parameters = {
        TemplateId: "2a2f3cf7-b61f-4238-86e1-be22829b3bd6",
    
        BaseTemplateIds: [
        ]
    }
    export const ContainerCenter75Parameters = {
        TemplateId: "944cf68e-51e3-43f2-b521-273b1d007589",
    
        BaseTemplateIds: [
        ]
    }
    export const ContainerFullBleedParameters = {
        TemplateId: "e1eb445d-2d66-45ac-aa79-ab0f9d9a6e6d",
    
        BaseTemplateIds: [
        ]
    }
    export const ContainerFullWidthParameters = {
        TemplateId: "e98728dd-0fb6-4e98-b756-86c5c9bff84f",
    
        BaseTemplateIds: [
        ]
    }
}    


