
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Layout.Divider Divider Parameters Layout
// @ts-ignore
import { Layout as LayoutDividerLayout } from "./Divider.model"

export namespace Layout.Divider {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Divider/Divider Parameters
    */
    export type DividerParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Divider/Divider Parameters as an Item
    */
    export type DividerParameters_Item = Omit<Item, 'fields'> & DividerParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Divider/Divider Parameters as a Component
    */
    export type DividerParameters_Component = ComponentProps & DividerParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/Divider/Divider Parameters
    */
    export type DividerParametersJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Layout.Divider.Constants {

    export const DividerParameters = {
        TemplateId: "6985bbf4-bc3c-4ea8-ac3c-60aac69f8863",
    
        BaseTemplateIds: [
        ]
    }
}    


