
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Layout.JumpNav Jump Nav Container Layout
// @ts-ignore
import { Layout as LayoutJumpNavLayout } from "./JumpNav.model"
// Template: Feature.HztlFoundation.Layout.JumpNav Jump Nav Container Folder Layout
// Template: Layout already imported
// Template: Feature.HztlFoundation.Layout.JumpNav Jump Nav Container Parameters Layout
// Template: Layout already imported
// Template: Feature.HztlFoundation.Layout.JumpNav Jump Nav Section Layout
// Template: Layout already imported
// Template: Feature.HztlFoundation.Layout.JumpNav Jump Nav Section Parameters Layout
// Template: Layout already imported
// Template: Feature.HztlFoundation.Lists.Accordion AccordionItem Parameters Lists
// @ts-ignore
import { Lists as ListsAccordionLists } from "./Accordion.model"

export namespace Layout.JumpNav {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container
    */
    export type JumpNavContainer =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container as an Item
    */
    export type JumpNavContainer_Item = Omit<Item, 'fields'> & JumpNavContainer

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container as a Component
    */
    export type JumpNavContainer_Component = ComponentProps & JumpNavContainer

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container
    */
    export type JumpNavContainerJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container Folder
    */
    export type JumpNavContainerFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container Folder as an Item
    */
    export type JumpNavContainerFolder_Item = Omit<Item, 'fields'> & JumpNavContainerFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container Folder as a Component
    */
    export type JumpNavContainerFolder_Component = ComponentProps & JumpNavContainerFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container Folder
    */
    export type JumpNavContainerFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container Parameters
    */
    export type JumpNavContainerParameters =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container Parameters as an Item
    */
    export type JumpNavContainerParameters_Item = Omit<Item, 'fields'> & JumpNavContainerParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container Parameters as a Component
    */
    export type JumpNavContainerParameters_Component = ComponentProps & JumpNavContainerParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Container Parameters
    */
    export type JumpNavContainerParametersJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Section
    */
    export type JumpNavSection =  {
        fields?: { 
            /**
            * Represents the Heading field (af0be331-00a7-4d9e-9cd6-340360e7f717).
            */
            heading?: Field<string>;

            /**
            * Represents the Jump Nav Heading field (d0668564-a7cf-4cb2-a1f2-10f6461586bd).
            */
            jumpNavHeading?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Section as an Item
    */
    export type JumpNavSection_Item = Omit<Item, 'fields'> & JumpNavSection

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Section as a Component
    */
    export type JumpNavSection_Component = ComponentProps & JumpNavSection

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Section
    */
    export type JumpNavSectionJson =  {
        
            /**
            * Represents the Heading field (af0be331-00a7-4d9e-9cd6-340360e7f717).
            */
            heading?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Jump Nav Heading field (d0668564-a7cf-4cb2-a1f2-10f6461586bd).
            */
            jumpNavHeading?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Section Parameters
    */
    export type JumpNavSectionParameters = ListsAccordionLists.Accordion.AccordionItemParameters &  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Section Parameters as an Item
    */
    export type JumpNavSectionParameters_Item = Omit<Item, 'fields'> & JumpNavSectionParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Section Parameters as a Component
    */
    export type JumpNavSectionParameters_Component = ComponentProps & JumpNavSectionParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/JumpNav/Jump Nav Section Parameters
    */
    export type JumpNavSectionParametersJson = ListsAccordionLists.Accordion.AccordionItemParametersJson &  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Layout.JumpNav.Constants {

    export const JumpNavContainer = {
        TemplateId: "a3dc84b7-cdf1-468c-92ef-c33dc4311075",
    
        BaseTemplateIds: [
        ]
    }
    export const JumpNavContainerFolder = {
        TemplateId: "9ea3bf4a-ed67-45db-bfad-8bb08cde31b3",
    
        BaseTemplateIds: [
        ]
    }
    export const JumpNavContainerParameters = {
        TemplateId: "2fe84a09-6c05-4213-bc4c-38d01f90289a",
    
        BaseTemplateIds: [
        ]
    }
    export const JumpNavSection = {
        TemplateId: "72bb023a-ce3e-4523-b4aa-16e54561d8d4",
    
        BaseTemplateIds: [
        ]
    }
    export const JumpNavSectionParameters = {
        TemplateId: "559fe8ea-8c7c-4468-bd54-59137b4966af",
    
        BaseTemplateIds: [
            "82b8c484-3e95-437f-92bb-f58ef08c2684", 
        ]
    }
}    


