
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Layout.Section Section Layout
// @ts-ignore
import { Layout as LayoutSectionLayout } from "./Section.model"
// Template: Feature.HztlFoundation.Layout.Section Section Folder Layout
// Template: Layout already imported
// Template: Feature.HztlFoundation.Layout.Section Section Parameters Layout
// Template: Layout already imported
// Template: Foundation.HztlFoundation _Theme Base
// @ts-ignore
import { Base as FoundationHztlFoundationBase } from "./HztlFoundation.model"

export namespace Layout.Section {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section
    */
    export type Section =  {
        fields?: { 
            /**
            * Represents the Description field (60b81123-e875-42a4-9063-e51484b598d4).
            */
            description?: Field<string>;

            /**
            * Represents the Display Center 75 field (94c4e031-20ff-4aca-87d9-27226a48e1f9).
            */
            displayCenter75?: Field<boolean>;

            /**
            * Represents the Remove Padding Bottom field (30d4d8ab-e294-481a-91c9-f5d38b1673a5).
            */
            removePaddingBottom?: Field<boolean>;

            /**
            * Represents the Remove Padding Left & Right field (ba36cfd3-34a0-4dbb-9389-211e9537bf18).
            */
            removePaddingLeftRight?: Field<boolean>;

            /**
            * Represents the Remove Padding Top field (8bbd14ca-a282-4cd6-8bac-6e3989c00ed7).
            */
            removePaddingTop?: Field<boolean>;

            /**
            * Represents the Title field (173c54c5-46e0-4358-8f16-a4e0fa376634).
            */
            title?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section as an Item
    */
    export type Section_Item = Omit<Item, 'fields'> & Section

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section as a Component
    */
    export type Section_Component = ComponentProps & Section

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section
    */
    export type SectionJson =  {
        
            /**
            * Represents the Description field (60b81123-e875-42a4-9063-e51484b598d4).
            */
            description?: {
                jsonValue: Field<string>
            };

            /**
            * Represents the Display Center 75 field (94c4e031-20ff-4aca-87d9-27226a48e1f9).
            */
            displayCenter75?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Remove Padding Bottom field (30d4d8ab-e294-481a-91c9-f5d38b1673a5).
            */
            removePaddingBottom?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Remove Padding Left & Right field (ba36cfd3-34a0-4dbb-9389-211e9537bf18).
            */
            removePaddingLeftRight?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Remove Padding Top field (8bbd14ca-a282-4cd6-8bac-6e3989c00ed7).
            */
            removePaddingTop?: {
                jsonValue: Field<boolean>
            };

            /**
            * Represents the Title field (173c54c5-46e0-4358-8f16-a4e0fa376634).
            */
            title?: {
                jsonValue: Field<string>
            };


    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section Folder
    */
    export type SectionFolder =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section Folder as an Item
    */
    export type SectionFolder_Item = Omit<Item, 'fields'> & SectionFolder

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section Folder as a Component
    */
    export type SectionFolder_Component = ComponentProps & SectionFolder

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section Folder
    */
    export type SectionFolderJson =  {
        

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section Parameters
    */
    export type SectionParameters = FoundationHztlFoundationBase.Theme &  {
        fields?: { 
            /**
            * Represents the Text Alignment field (80d5c1f8-7046-42e0-9833-48f6efd9db1d).
            */
            alignment?: Field<string>;
        }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section Parameters as an Item
    */
    export type SectionParameters_Item = Omit<Item, 'fields'> & SectionParameters

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section Parameters as a Component
    */
    export type SectionParameters_Component = ComponentProps & SectionParameters

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/Section/Section Parameters
    */
    export type SectionParametersJson = FoundationHztlFoundationBase.ThemeJson &  {
        
            /**
            * Represents the Text Alignment field (80d5c1f8-7046-42e0-9833-48f6efd9db1d).
            */
            alignment?: {
                jsonValue: Field<string>
            };


    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Layout.Section.Constants {

    export const Section = {
        TemplateId: "65eecb2c-7466-4837-970a-d6501615f08a",
    
        BaseTemplateIds: [
        ]
    }
    export const SectionFolder = {
        TemplateId: "698c2002-c1b7-45b6-b838-833c6036f64c",
    
        BaseTemplateIds: [
        ]
    }
    export const SectionParameters = {
        TemplateId: "3109db8b-cf49-402b-9864-2ad4fff0a6f4",
    
        BaseTemplateIds: [
            "2d5e2037-3132-4bcf-8654-79d99111292e", 
        ]
    }
}    


