
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */

// @ts-ignore 
import { Field, ImageField, FileField, LinkField, Item } from '@sitecore-content-sdk/nextjs';
import { ComponentProps } from 'lib/component-props';
// Template: Feature.HztlFoundation.Layout.SidebarLayout Sidebar Layout Layout
// @ts-ignore
import { Layout as LayoutSidebarLayoutLayout } from "./SidebarLayout.model"

export namespace Layout.SidebarLayout {

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/SidebarLayout/Sidebar Layout
    */
    export type SidebarLayout =  {
        fields?: {         }

    }

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/SidebarLayout/Sidebar Layout as an Item
    */
    export type SidebarLayout_Item = Omit<Item, 'fields'> & SidebarLayout

    /**
    * Represents the template /sitecore/templates/Feature/HztlFoundation/Layout/SidebarLayout/Sidebar Layout as a Component
    */
    export type SidebarLayout_Component = ComponentProps & SidebarLayout

    /**
    * Represents the GraphQL template /sitecore/templates/Feature/HztlFoundation/Layout/SidebarLayout/Sidebar Layout
    */
    export type SidebarLayoutJson =  {
        

    }
}




/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

export namespace Layout.SidebarLayout.Constants {

    export const SidebarLayout = {
        TemplateId: "f3545dae-86c6-4d93-b4e1-55634b74d4d3",
    
        BaseTemplateIds: [
        ]
    }
}    


