---
ID: "c57d2a51-387b-4291-ad12-fe5e06ac6ede"
Parent: "c5d8dad0-0c78-4a16-a6f1-de30e51b9b55"
Template: "c5d8dad0-0c78-4a16-a6f1-de30e51b9b55"
Path: /sitecore/templates/Feature/HztlFoundation/Lists/VideoCardItem/VideoCardItem Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "60cbe701-d0cd-44ee-ac48-0347233f9b68"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dkakade@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250619T082205Z
