---
ID: "e1a0b15c-4e05-4dde-9a4e-55ef5f4aebb9"
Parent: "e98728dd-0fb6-4e98-b756-86c5c9bff84f"
Template: "e98728dd-0fb6-4e98-b756-86c5c9bff84f"
Path: /sitecore/templates/Feature/HztlFoundation/Layout/Container/Container Full Width Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "15d86a1c-0cba-4d71-8226-92e5116c5ab8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\anandakumar.a@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250708T202110Z
